### ISSUE TITLE
Meeting List changes

### ISSUE THREAD

**Issue by nutjob4life** [RecoveryDharma/website#1]
## 🤔 Tell Us About the Feature

Goal: simplify finding a meeting.

## 🎇 What Solution You'd Like

1. Make "Find a Meeting" go directly to the [2020 meeting list](https://recoverydharma.org/meeting-list). This is the all-caps "FIND A MEETING" with icon right on the [home page](https://recoverydharma.org/).
2. Remove all other meeting list pages from the site (but leave redirections to the [2020 meeting list](https://recoverydharma.org/meeting-list) in case of bookmarks).
3. On the page at https://recoverydharma.org/meeting-list, on the section "Online Meetings", replace the text on item #2 with links directly to the timezone tabs on the meeting spreadsheet.

## 〽️ Alternative Ideas

No other ideas at this tie.

**Comment by KrisRecoveryDharma** [comment]
Close.  
Yes: Remove all other current links
Add the links to the tabs in the menu (this is redundant to the 2020 meeting list page)

**Comment by nutjob4life** [comment]
OK, the MEETINGS menu item will look something like this:
```
MEETINGS
--------
All Meetings
By Timezone ▶️
    Eastern
    Pacific
    American Samoa
    New North Wales
    ...
Submit/Update Meeting
```
with each link under "By Timezone" will be a corresponding link to https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/view#gid=1085980187

In addition, the "Submit/Update" link will allow people to submit a new meeting or update an existing one.

**Comment by KrisRecoveryDharma** [comment]
Next step: Create a query from the spreadsheet that shows active in-person meetings.

**Comment by nutjob4life** [comment]
Hah! Yes @KrisRecoveryDharma … but for that, I recommend [filing a new issue](https://github.com/RecoveryDharma/website/issues/new/choose) 😉

**Comment by nutjob4life** [comment]
Changes installed and are now live on https://recoverydharma.org/ with redirects installed, updated menu items, and fixed home page link.

Feel free to re-open this issue if the changes don't work as expected.

**Comment by KrisRecoveryDharma** [comment]
Umm... it looks the same to me perhaps the changes didn't go live?

**Comment by KrisRecoveryDharma** [comment]
Content Change:
Meeting list page:  https://recoverydharma.org/meeting-list

Replace the text under Online Meeting with the list of links to the meeting list tabs. 
Current: ![image](https://user-images.githubusercontent.com/70176719/91753404-dbe39100-eb95-11ea-934d-9914d500c90c.png)

Update: 
FIND A MEETING
Online Meetings
- Click on the link below for meetings listed in a time zone near you
(Use Hyperlink text that reflects the menu - use your judgement for best formatting)
- US Pacific - http://pacific.recoverydharma.guide
- US Eastern - http://eastern.recoverydharma.guide
- United Kingdom - http://uk.recoverydharma.guide
- Central Europe - http://europe.recoverydharma.guide
- Japan - http://japan.recoverydharma.guide
- East Australia - http://australia.recoverydharma.guide

- Women/Nonbinary - http://womxn.recoverydharma.guide

**Comment by nutjob4life** [comment]
Re-opened on @KrisRecoveryDharma's behalf

**Comment by nutjob4life** [comment]
Updated page to reflect request in https://github.com/RecoveryDharma/website/issues/1#issuecomment-683954079

**Comment by KrisRecoveryDharma** [comment]
Sorry, one more change: 
Replace the phrase "Issue Affinity" with the phrase:  Topic

**Comment by nutjob4life** [comment]
Issue well and truly closed!
