### ISSUE TITLE
Change Links on Accordian boxes - Beginner's Page

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#100]
Hi Tom, 
 - 
I thought I could edit the text and create a link, but it is not working for me.  
I would like the Beginners Page to look the same as the Start A Meeting Page. 

https://recovery-dharma.flywheelsites.com/get-started/beginners/

FRIENDS AND MENTORS ACCORIAN BOX
Add a green button at the bottom of  of the box:  "Friends and Mentors"
Link that text to: https://recovery-dharma.flywheelsites.com/resources/friends-mentors/
Remove the link that is connected to the whole box. 

GROWTH ACCORDION BOX
Add a green button at the bottom of  of the box:  "Glossary"
Link that text to: https://recovery-dharma.flywheelsites.com/glossary/
Remove the link that is connected to the whole box. 

MEDITATION ACCORDION BOX
Add a green button at the bottom of  of the box:  "Meditations"
Link that text to: https://recovery-dharma.flywheelsites.com/resources/meditations/
Remove the link that is connected to the whole box. 

INQUIRY & INVESTIGATION ACCORDION BOX
Add a green button at the bottom of  of the box:  "Inquiry"
Link that text to: https://recovery-dharma.flywheelsites.com/resources/inquiry/
Remove the link that is connected to the whole box.

**Comment by tom-raley** [comment]
Hey @KrisRecoveryDharma made these changes, let me know if it all looks right.
