### ISSUE TITLE
404 Error @ https://recovery-dharma.flywheelsites.com/?page_id=207514 (Meetings & Events Link)

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#102]
## 🐛 Describe the Bug

There is a 404 error when clicking on "Meetings & Events", which leads to:
https://recovery-dharma.flywheelsites.com/?page_id=207514

## 📜 How To Reproduce

1. Go to https://recovery-dharma.flywheelsites.com
2. Click on "Meetings & Events" (or click on Accordian first)
3. Notice at URL "https://recovery-dharma.flywheelsites.com/?page_id=207514" there is a 404 error

## 🔎 Expected Behavior

I believe we want to see: https://recovery-dharma.flywheelsites.com/find-a-meeting/

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/70724023/156462791-0f109e5a-5ea8-4336-9f83-5d76676e8b2d.png)

**Comment by KrisRecoveryDharma** [comment]
Thank you Tom A,

Yes we are in the midst of finishing that page.  It is pretty much set.  I
am c9nfident it will be resolved before launch or very soon after tomorrow
morning

**Comment by KrisRecoveryDharma** [comment]
Oh!  You know what?
Maybe not!
Thank you

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @unity1979 This should be resolved. Let me know if you're still seeing issues.

**Comment by KrisRecoveryDharma** [comment]
I just checked it out and it looks great!

**Comment by KrisRecoveryDharma** [comment]
Complete!
