### ISSUE TITLE
At Find A Meeting page, Online Meetings need updates/removals

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#103]
## 🐛 Describe the Bug

At https://recovery-dharma.flywheelsites.com/find-a-meeting/ some links need Updates or Removal.

(A) These links do not work: 
1. Nepal - Tab no longer exists. (Remove please)
2. New Zealand - Tab no longer exists. (Remove please)  

(B) These links should be renamed for more clarity: 
3. Hawaii - Rename to "Hawaii Time (USA)" 
4. Pacific US - Rename to "Pacific Time (USA)
5. Mountain US - Rename to "Mountain Time (USA)"
6. Central US - Rename to "Central Time (USA)"
7. Eastern US - Rename to "Eastern Time (USA)"
8. Atlantic - Rename to "Atlantic Time (Canada)"
9. UK - Rename to "UK Time (London)"
10. Central Europe - Rename to "Central Europe Time (Berlin)"
11. Japan - Rename to "Japan Time (Tokyo)"
12. Australia - Rename to "East Australia Time (Melbourne)"

(C) Finally, the Women/Nonbinary meeting list is now part of the more inclusive Affinity meetings list (men/bipoc/lgbtq+). So:
13a. Women/Nonbinary - URL should be replaced with: https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1394082114&single=false 
13b. Women/Nonbinary - Text should be replaced with: "**All Affinity & Topic Meetings List** (AFFINITIES: Bipoc, Lgbtqia+, Men+Nonbinary, Women+Nonbinary. TOPICS: Beginners, Codependency, Eating+Food, Family Support, Heart Practices, Inquiry, Love&Lust, Mental Health, Mentorship, Speaker Meetings.)" 

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/70724023/156475905-aa7c0045-3982-429b-9631-7f38e1e837ac.png)

**Comment by KrisRecoveryDharma** [comment]
I like this idea.
Let's add it to the list of to-do's.
Not crucial for functioning, but helpful.

**Comment by KrisRecoveryDharma** [comment]
Done!
