### ISSUE TITLE
Glossary: Sila has no definition when clicked on

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#104]
## 🐛 Describe the Bug

At https://recovery-dharma.flywheelsites.com/glossary/

The glossary term Sila has no definition revealed when clicked on.

## 📜 How To Reproduce

1. Go to https://recovery-dharma.flywheelsites.com/glossary/
2. Click on Sila
3. Notice nothing happens

## 🔎 Expected Behavior

Sila is removed. (It is never used in the book).

## 🖼 Screenshots

<img width="540" alt="image" src="https://user-images.githubusercontent.com/70724023/156555363-5f9eecf7-bfb1-4e68-91ad-2b48cba515c3.png">

**Comment by KrisRecoveryDharma** [comment]
Sila was added but was not part of the original list. 
It has been deleted for now. 
Resolved
Thanks!
Kris
