### ISSUE TITLE
Sangha-Groups: Typos

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#105]
## 🐛 Describe the Bug

On https://recovery-dharma.flywheelsites.com/get-started/sangha-groups/ there are a handful of typos

## 📜 How To Reproduce

1. Go to https://recovery-dharma.flywheelsites.com/get-started/sangha-groups/
2. Click on Meetings
3. Notice typos:
• responsibilties → responsibilities
• facilitaor → facilitator
• recommeded → recommended 
• postitions → positions

## 🔎 Expected Behavior

Typos corrected
• responsibilties → responsibilities
• facilitaor → facilitator
• recommeded → recommended 
• postitions → positions

## 🖼 Screenshots

<img width="477" alt="image" src="https://user-images.githubusercontent.com/70724023/156556869-89b8a847-3b6f-425d-b488-684569fe23e5.png">

**Comment by unity1979** [comment]
Also in Growth.

4. Click on dropdown Growth:
5. Notice Buddist → Buddhist

Should be corrected to Buddhist

**Comment by KrisRecoveryDharma** [comment]
Resolved
