### ISSUE TITLE
In Meetings page, Text color is very hard to read/blends into graphic background

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#106]
## 🐛 Describe the Bug

On https://recovery-dharma.flywheelsites.com/meetings/ it is hard to read
1. The Practice and text (when scrolling over the Top Left of 6 rectangles)
2. The About Meetings and text

## 📜 How To Reproduce

1. Go to https://recovery-dharma.flywheelsites.com/meetings/
2. Scroll down below Meeting Materials 
3. Mouse Over the top left black&white rectangle and notice it's difficult to read the Practice text
<img width="326" alt="image" src="https://user-images.githubusercontent.com/70724023/156558185-bbf3d606-8746-4989-ae4f-e14aa78c9d6d.png">
6. Scroll down further to About Meetings
7. Notice it is hard to read the entire blurb
<img width="950" alt="image" src="https://user-images.githubusercontent.com/70724023/156558275-70c82675-0959-4163-962a-48a52b7d5770.png">

## 🔎 Expected Behavior

The text color should follow the scheme of the others—they should also be White.

**Comment by KrisRecoveryDharma** [comment]
Thanks Tom, 
These two items are design questions. 
Lacey and Tom are the team members focused on this aspect of the site. 

Thanks!

**Comment by unity1979** [comment]
Resolved
