### ISSUE TITLE
in Meetings page "We are...leaderless" is false, contradicting, and has caused real harm to doing Service in RD

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#107]
## 🤔 Tell Us About the Feature

Simple proposal: "We are decentralized and [peerled]"

On the page https://recovery-dharma.flywheelsites.com/meetings/ is an important, controvertial, false quote: 

<img width="418" alt="image" src="https://user-images.githubusercontent.com/70724023/156660853-44e43ce4-3186-43b5-9446-ae2e5007d1a4.png">

"We are decentralized and **leaderless**," where other parts of the website (Sangha Groups references "One leader often ends a business discussion..." and "As leader servants..."). This is contradictory to the website, other parts of the book, but moreover has been long problematic for getting into Service at group level.
 
This seems innocent. 

In my observation, the word "leaderless" (rather than simply "peerled") has resulted in surprisingly disproportionate and unnecessary confusion, and has had  strongly negative effects on being of service. Newcomers will say, “Then why is that person leading the meditation?” Or “They are acting like a leader, but I thought RD is leaderless.”

In practice, without a doubt, we do have leaders. I dare say, *gulp*: it's good to have a leader! Especially in recovery, we need and benefit from strong leaders.

The simplest example is that every week, someone **leads a guided meditations**. 

But here's why it's important. A greater example is to look at any Sangha and you will find **selfless RD leaders** who serve as fine examples of service for newcomers, who are passionate about recovery dharma, without who the rooms of Recovery Dharma would cease to exist. 

"Leaderless" is perhaps the single most damaging word to service in our entire book. This is an important issue that has come up again and again and affects every newcomer, and we can begin to clarify, now with this website launch.

## 🎇 What Solution You'd Like

The quote can simply say → "We are decentralized and [peerled]"

## 🗺 Context

The suggestion is to use a word that isn't false. It can be replaced by a word in brackest, like [peerled], just like done in The Practice:
https://recovery-dharma.flywheelsites.com/project/the-practice/

<img width="246" alt="image" src="https://user-images.githubusercontent.com/70724023/156661094-4ba411a0-3fd0-4411-b06f-b11de0b30770.png">

**Comment by unity1979** [comment]
Again, this _seems_ trivial! In practice, "leaderless" is untrue, repeatedly creating confusion. Here is an example in practice, where the use of the word "lead" is removed from the script. See http://bit.ly/rdo-meeting-script-discussion screenshot below.

<img width="757" alt="image" src="https://user-images.githubusercontent.com/70724023/156605032-cc42a139-21a7-4131-8cf6-68418700adba.png">

In the book page 106, the script uses the word "lead". This is contradictory and has resulted in confusion. 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/70724023/156606969-5e0de1eb-ddee-4fe3-97bd-0f8bb426062e.png">

Saying "leaderless" is trying to destroy something that already exists, peer-led is compatible with our program.

**Comment by nutjob4life** [comment]
Outside my bailiwick! I just handle the EventOn plugin. Hope y'all can figure out the right verbiage.

**Comment by KrisRecoveryDharma** [comment]
Hey  Thomas, 
This is a worthwhile discussion and debate, but not a part of the website team.  I am happy to keep this open and unresolved for now. 

If you have an alternative quote you'd like to suggest, feel free to post it here. The one on Equanimity and balance is about Effort; not meetings. 

Thanks!
Kris

**Comment by KrisRecoveryDharma** [comment]
Thank you for the feedback. 
I'm going to close this for now. 
Feel free to open it back up if you have an alternative quote you want to propose. 
Thanks,
Kris

**Comment by unity1979** [comment]
Thank you for allowing me to feel heard, Kris. Great suggestion on proposing an alternative. The remainder of the same quote is really good, so perhaps:

**Proposed Replacement Quote:**
"[There] are no rules to follow other than that the meeting should be an open, safe, and accessible space that tries to uphold our core principles of mindfulness, compassion, forgiveness, and generosity." — Recovery Dharma, Page 52

(Previous Quote for reference)
<img width="462" alt="image" src="https://user-images.githubusercontent.com/70724023/156671357-7c4bbbb1-ca95-4cf5-96ab-4c8c5594925f.png">
