### ISSUE TITLE
The About Page has lost his Banner Art and Title

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#109]
Hi Tom R

Uh-Oh! 
The artwork and title of the About Page have disappeared!

https://recoverydharma.org/about/
![image](https://user-images.githubusercontent.com/70176719/156661199-0b0de9fe-e7d3-4cc1-94e2-b20f15cec8a9.png)

Thank, 

Kris

**Comment by tom-raley** [comment]
@KrisRecoveryDharma I have no idea why this is happening. It's fine when logged in and fine on the flywheel site. I'll keep investigating, but Firespring might know?

**Comment by tom-raley** [comment]
@KrisRecoveryDharma I think this is fixed if you want to check again on your end.

**Comment by KrisRecoveryDharma** [comment]
Yes!
It is fine now
It must have been a temp glitch thing
Thanks!
