### ISSUE TITLE
Redirect Meeting URLs

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#11]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [X ] replacing existing content

**https://recoverydharma.org/meetings**  needs to point to our main, active meeting list. 

I am not sure if the solution is to redirect or to make it direct.  There are many people out there who have the page bookmarked - including our organizational partners.  Last week, it redirected to /meeting-list.  Today it goes back to the 12 Step Database. 

I trust your judgement on which is best. Just so long as it leads to the current active list. 

Thanks!

Kris

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma I am *not* seeing the URL `https://recoverydharma.org/meetings` go to the 12 Step Meeting List database as of today, 2020-09-06.

What I currently see:

- Redirection from `https://recoverydharma.org/meetings` → `https://recoverydharma.org/meeting-list`
- `https://recoverydharma.org/meeting-list` gives page content

Either way, users end up at a meeting list.

Could you provide some screen shots (include the address bar in your browser) that show the 12 Step Meeting List?

**Comment by KrisRecoveryDharma** [comment]
It looks like it is working fine now. 
Thanks!

**Comment by nutjob4life** [comment]
Woot woot! Great to hear @KrisRecoveryDharma! Thank you for checking 🎉
