### ISSUE TITLE
Events Page is not pulling events from the Blog

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#110]
Hi Tom R, 

The events page should be pulling anything that is categorized as an Event. The results should display as a list of all past and current events - with the current events at the top of the page. 

https://recoverydharma.org/events/

We need to either make sure that event posts are correctly categorized and/or we need to see if there is a broken link with the page. 

Thanks!

Kris

**Comment by tom-raley** [comment]
@KrisRecoveryDharma I'll take a look. For what it's worth, this is not the page I set up for Events. Firespring must have changed it for some reason. I'll see if it's easy to revert back to the version I had created :)

**Comment by tom-raley** [comment]
@KrisRecoveryDharma Looks like Firespring installed an events plugin that was overwriting the URL I had for the events page. I changed that plugin URL to events-plugin, so now ours is working again :)
