### ISSUE TITLE
Find a meeting is not showing up

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#112]
Find a meeting is showing the navigation bars, but no content

https://recoverydharma.org/find-a-meeting/
![image](https://user-images.githubusercontent.com/70176719/157321301-39af646a-9a00-468b-bb6f-2c5ddde5c2dc.png)

**Comment by KrisRecoveryDharma** [comment]
It must have been a glitch! It is working now
Kris

**Comment by unity1979** [comment]
Additional info: The meeting-list page seems to be Nested within the meeting-list page

![image](https://user-images.githubusercontent.com/70724023/157340260-92b013b7-84db-4c36-86c1-61c63ceeb6bd.png)

**Comment by unity1979** [comment]
(Side note: The Contact page and Book page also appear with double-navigation bar. See #113)
• https://recoverydharma.org/book/
• https://recoverydharma.org/contact/

**Comment by KrisRecoveryDharma** [comment]
Closing and consolidating with the other issue. 

Kris

**Comment by KrisRecoveryDharma** [comment]
Resolved - It is showing up now!
