### ISSUE TITLE
Book & Contact pages not showing up correctly (similar to find-a-meeting)

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#113]
The navigation bar appears twice (possibly nested). It looks like the find-a-meeting page bug.
• https://recoverydharma.org/book/
• https://recoverydharma.org/contact/

2 Screenshots:
• https://recoverydharma.org/book/
![image](https://user-images.githubusercontent.com/70724023/157341040-66837eef-227b-4783-a313-04f82c66921d.png)

• https://recoverydharma.org/contact/
![image](https://user-images.githubusercontent.com/70724023/157341078-5d9596cd-b0e4-474e-bd61-7ff73d262c57.png)

**Comment by KrisRecoveryDharma** [comment]
Consolidating - Adding Find A meeting to this Issue
https://recoverydharma.org/find-a-meeting/

New insight - the banners are not showing up on these pages. The rest of the content seems to be fine.

**Comment by KrisRecoveryDharma** [comment]
Resolved! They are showing up now! :-)
