### ISSUE TITLE
SEO (?) for Recovery 

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#115]

**Comment by KrisRecoveryDharma** [comment]
The board was talking about our recent issue with amazon.  One of the things we noticed was that when someone searches for the recovery dharma book, it does not pop up in the list. 

Are there any steps we can take to help make sure it pops up on the list?

**Comment by unity1979** [comment]
Could not reproduce (fortunately?). I used these steps and the RD Book from Amazon always appeared within the top few results. Search term “Recovery Dharma Book” with search engines used: Google, Brave, Bing, DuckDuckGo, Ecosia, Qwant. Also used Amazon search and it showed up. 

Were there different steps to reproduce?

screenshot
![949B06CB-6095-4EC1-A05D-E7A39A404A91](https://user-images.githubusercontent.com/70724023/158109992-1fddd587-40c7-436c-b84a-86100f60ccf6.png)
