### ISSUE TITLE
2022 Summit Banner

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#119]
https://recoverydharma.org/2022-sangha-summit/

Wish list - if you have time and if it's possible. 

Goal:  Get the two buttons for Schedule and Register onto the same screen with the logo and title. 

Idea: 
- Move the round logo to the left, 
- Put Sangha Summit 2022 and the dates to the right. 
- that will move up the buttons so that they are on the same page
- Put all of it on top of the brand color blue-green gradient

Similar to the arrangement on this page from the UUA, except all in the blue-green banner at the top. 
https://www.uua.org/ga

...if you think that would look okay - that the letters and the buttons would not disappear

This is not essential.  It is a wish List

Thank you!

**Comment by tom-raley** [comment]
@KrisRecoveryDharma Just updated the page. Let me know if this works!

**Comment by KrisRecoveryDharma** [comment]
Perfection!  Thank you!
Kris
