### ISSUE TITLE
Request: New Meeting List layout: See image for new left side layout for Affinity Online meetings

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#124]
To logically separate Affinity Online meetings from the Online (Timezone) Meetings, I wanted to suggest this layout:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/70724023/166800119-aa3c87d3-d360-4ee1-a092-534ed304bfc6.png">

What do you think?

**Comment by unity1979** [comment]
Old Layout: 
<img width="673" alt="image" src="https://user-images.githubusercontent.com/70724023/166800696-aca207c9-84f8-427a-8a9f-b7f9eb7b90ae.png">

**Comment by KrisRecoveryDharma** [comment]
Iike it!
Will work on ot this weekend

**Comment by unity1979** [comment]
(leaving the text here for notes)

In-Person Meetings
[🪑In-Person Meetings (Spreadsheet)](https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?fbclid=IwAR3S9VWQhc7xX1gd2KaXsk-ILX0a_Q1Blki-uP-AF7IAKdRYAkxMcW6WcgI#gid=1492891510)

Affinity Online Meetings
[💞Affinity Meetings Guide (Topic-Focused or Identity-Focused)](https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?fbclid=IwAR3S9VWQhc7xX1gd2KaXsk-ILX0a_Q1Blki-uP-AF7IAKdRYAkxMcW6WcgI#gid=1492891510)

Affinity groups are Special-Interest meetings with a focus on a specific topic or identity.

(**Topic examples**: Eating, Codependency, Beginners, Precepts, etc. **Identity examples**: LGBTQIA+, Women, Men, BIPOC.)

**Comment by KrisRecoveryDharma** [comment]
Resolved
