### ISSUE TITLE
Meeting list requires URL updates for easy access to 🪑In-Person meetings

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#125]
@ recoverydharma.org/meeting-list

Many people have been confused about being unable to find their In-Person meetings, mistakeningly believing their meetings have been removed.

This can be eased by changing the URL to enable tabs at the top to be shown like so:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/70724023/166802324-c2e011e0-2ae3-4dc2-b347-b5ef7c25c19b.png">

For this, the meetings URL should be updated as follows:

In Person Meetings (Spreadsheet)
http://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1492891510&single=false

In Person Meetings (Spreadsheet) rename to
"🪑In-Person Meetings (Spreadsheet)"

Hawaii Time (USA)
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=188599084&single=false

Pacific Time (USA)
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=496973103&single=false

Mountain Time (USA)
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1567715471&single=false

Central Time (USA)
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1870057131&single=false

Eastern Time (USA)
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1997228258&single=false

Atlantic Time (Canada)
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=862403844&single=false

Brazil Time (Sao Paulo)
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1698426725&single=false

UK Time (London)
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1799102808&single=false

Central Europe Time (Berlin)
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1971437393&single=false

Japan Time (Tokyo)
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1497061528&single=false

East Australia Time (Melbourne)
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1833391122&single=false

Affinity and Topic Meetings
docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1394082114&single=false

Affinity and Topic Meetings renamed to
"💞Affinity Meetings (Topic & Identity Focused)"

Women and Nonbinary Meetings (remove)
(It no longer exists because it lives in Affinity Meetings)

Thank you

**Comment by KrisRecoveryDharma** [comment]
I am not understanding the solution through text.  Let's chat by phone.

**Comment by KrisRecoveryDharma** [comment]
Resolved

**Comment by KrisRecoveryDharma** [comment]
Resolved
