### ISSUE TITLE
Meetings List: "Women and Nonbinary Meetings" link does not work as expected (should be removed)

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#126]
At: https://recoverydharma.org/find-a-meeting/

The link "Women and Nonbinary Meetings"

No longer exists, because it lives in part of the Affinity Meetings tab.

Steps to Reproduce:
Click on: [Women and Nonbinary Meetings](https://docs.google.com/spreadsheets/u/4/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1394082114&single=false#)

Notice:
The Women/NB meetings list does not exist.

Expected Behavior:
The link "Women and Nonbinary Meetings" should be removed

**Comment by KrisRecoveryDharma** [comment]
Resolved
