### ISSUE TITLE
2022 Sangha Summit Scholarship Form

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#129]
# ✋ Hold it!

I gave it a go at creating the content.  I discovered that creating a new page is one step above my current skill level. 

## 📕 Summary

NEW URL:  https://recoverydharma.org/2022-sangha-summit/scholarship-app

This form will be used by members who want to apply for a registration scholarship to the 2022 Sangha Summit. 

## 🔍 Details

Replace this with detailed information about the request. For new content, make sure to mention
- Where it should live on the Recovery Dharma site  - Under the 2022 Sangha Summit
- 
- How it should be hyperlinked from existing pages - It should be linked from the 2022 Sangha Summit Page. We have not yet considered where/how.  If you have an idea, then feel free to add it. Or I can add it later. There will also be an article in the news section, but it has not yet been written.

For changes, tell where and what should be changed. For deletions, tell what to delete and if redirections should be left behind.

Header: IDEA Committee Scholarship Application
Subtitle: 2022 Sangha Summit

Description: This year, the IDEA Committee of the RDG Board ( Inclusion, Diversity, Equity, and Accessibility), is able to offer registration scholarships for the Sangha Summit.  We are offering 10 scholarships for In-Person Registration and 40 Scholarships for Online Registration

To apply, complete the form below. 
If you have any questions, please contact [info@recoverydharmaglobal.org](mailto:info@recoverydharmaglobal.org) 

	.
Section Title Header: Application

Field 1: Person Requesting Scholarship:  (Required
Field 2: Local Sangh Group:  (optional)
Field 3: Email:   Required)
Field 4: Phone: (Required) 
Field 5: Mailing Address: (Required) 

Check Box: Person of Color
Check Box: LGBTQIA+
Check Box: Household earning less than $40k per year
Check Box: Military or Veteran
Check Box: Person with dis/abilitites
Check Box: None of the above

Please describe if your Local Sangha Group has organized any fundraising activities to support your attending the event:  (Require)

Please include any further information you’d like to share with us here: (Optional)

## 📈 Attachments

For new content, don't forget to attach the file you want uploaded to the portal. If it's just text, you can even paste or type it in right here.

**Comment by tom-raley** [comment]
@KrisRecoveryDharma Page is live here: https://recoverydharma.org/2022-sangha-summit/scholarship-app/

Let me know your thoughts!

**Comment by KrisRecoveryDharma** [comment]
This looks great!
Thanks!

**Comment by tom-raley** [comment]
Sounds good! I'll leave the issue open till we figure out how we want to link it on the main page.

**Comment by Lacey-boop** [comment]
Thanks Thom, Hi @tom-raley could you add a section  right under the address forms that reads:
Type of scholarship requested (Required):
-In Person
-Online

**Comment by tom-raley** [comment]
@KrisRecoveryDharma I am actually traveling all weekend and won’t really have access to a computer.

But if you go in to the Forms section in the back end of Wordpress and edit the scholarship form, you should be able to drag and drop a checkbox field into the form and once you save, it’ll update the front end.

Let me know if that works, otherwise I’ll try and make the update later today.

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @Lacey-boop @unity1979 the scholarship form has been updated with the radio buttons. Let me know if we need anything else!

**Comment by unity1979** [comment]
Closing issue, all has been addressed

**Comment by KrisRecoveryDharma** [comment]
I am familiar enough now with word press that I can add it.
Kris
