### ISSUE TITLE
Summit landing page appears misformatted, with double-navigation menu

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#130]
## 🐛 Describe the Bug

After clicking on the initial "Click here to go to the Sangha Summit page! button
![image](https://user-images.githubusercontent.com/70724023/171671784-9ee610e5-c870-467b-88cd-842cec9504cc.png)

I ended up on a misformatted sangha summit page at https://recoverydharma.org/2022-sangha-summit/

This occurred on:
• iPhone Chrome
• mac OS Chrome
• mac OS Safari
(screenshots provided)

## 📜 How To Reproduce

Put steps to reproduce the behavior here, **including URLs**, such as
1. Goto www.recoverydharma.org
2. Click on "click her to go to the sangha summit page!"
3. Notice misformatting (see screenshots)
4. Notice that there are two oddly placed Magnifying glasses 🔎, reminiscent of the double-navigation-menu bug
5. Notice when you extend the width of the window enough, the navigation menu text appear twice. (see 2nd screenshot)
6. Happens 100% of the time when I try it

## 🔎 Expected Behavior

Should not have double navigation menus

## 🖼 Screenshots

MacOs Chrome (smaller width)
<img width="967" alt="Screen Shot 2022-06-02 at 8 50 02 AM" src="https://user-images.githubusercontent.com/70724023/171673625-10290bdf-533b-44da-971c-cf4ae9e22e30.png">

MacOS Safari (extended width—reveals the text of navigation menu)
![Screen Shot 2022-06-02 at 8 49 10 AM](https://user-images.githubusercontent.com/70724023/171673770-0497780c-8a2a-4899-b560-dc30936e4c5a.png)

## 🕵️‍♀️ Extra Details

🙏

**Comment by tom-raley** [comment]
@unity1979 This seems to be fixed now. I have no idea why it keeps happening. @KrisRecoveryDharma @Lacey-boop Firespring might know more?

**Comment by unity1979** [comment]
Closing issue as it seems intermittent and fixes itself!
