### ISSUE TITLE
Banner is not loading

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#131]
The banner is not loading for the Sangha Summit Page

💥 https://recoverydharma.org/2022-sangha-summit/

## 🔎 Expected Behavior
The banner shows when going to the page - including the links to register, apply for a scholarship and participate in the Survey Says

## 🖼 Screenshots

If you have any screenshots that help, attach them.
![image](https://user-images.githubusercontent.com/70176719/174118707-9e2bcc51-f489-42e7-a9d0-c64ca173d129.png)
![image](https://user-images.githubusercontent.com/70176719/174118847-2d72eb8b-643f-44f9-a48d-2ff09de295d8.png)

## 🕵️‍♀️ Extra Details

If you think it'll help, you can add any of the following:
-   Platform
    -   Desktop browser Chrome 
-   Noticed Time of day  12:22 pm ET

-  ADDITIONAL CONTEXT
* I updated the banner last night to add buttons. I'm wondering if I messed it up. 

*  Perhaps we should consider moving buttons to the first article instead of the banner. Even if my additions didn't mess it up, the banner missing is a regular occurrence on our site, and losing it means losing the buttons. 

Thanks all!

Kris

**Comment by unity1979** [comment]
Closing issue as it seems intermittent. Can open again if it re-appears

**Comment by KrisRecoveryDharma** [comment]
Fixed.

Thsnks!
