### ISSUE TITLE
Getting RDG Site to populate at the top of Google searches

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#133]
Hey Friends, 

I received a query from a board member about RDG not popping up until the 10th page of a Google Search.  
My response was that there is an app and a process for that, but we have not prioritized it yet. First we have had other priorities, but also that we wanted to get the whole site up and running - particularly the meeting list - before making a big splash on the Internet.  

If I remember correctly, there are a few relatively easy steps we can take to get ourselves populated at the top of a google search. 

QUESTION: 
Is this something that we have the capacity to address with our internal team, or would it be more effective to ask Firespring to take this on as a project?

**Comment by nutjob4life** [comment]
Ugh.

It looks like some settings left on in development that prevent the site from being indexed were _left on_ once it went into production. For example, this box was checked:

![Screen Shot 2022-07-10 at 3 15 34 PM](https://user-images.githubusercontent.com/814813/178160803-0b75b5e5-e46b-4af1-9e29-8e29fbe69d0d.png)

I've unchecked it. I'm now going through numerous other settings to identify thinks that might be harmful to search engine optimization (SEO). Stand by!

**Comment by nutjob4life** [comment]
Here's what I've done so far:

- Added site tagline (meta desc)
- Added sitemap.xml
- Added Google site verification to `recoverydharma.org` DNS TXT record
- Added `recoverydharma.org` to Google Search Console

And most importantly:

- Fixed the `robots.txt` file which was telling every search engine to steer clear of our site 😱

I'm waiting on caches to clear so the new `robots.txt` file starts to circulate and get picked up by the various search engines. The fact this "development" style of `robots.txt` got left on from development `.flywheelsites.com` → production `recoverydharma.org` has probably gotten us delisted in tremendous ways.

Anyway, now we have to wait to see if the fix fixes it.

We should also mention to Firespring that `Disallow: /*?` got left on in `robots.txt` in production and made us anti-SEO. I tend to recall that part of our earlier calls with them included SEO setup.

**Comment by KrisRecoveryDharma** [comment]
Thank you!  
I will notify the board member that we've found a solution!
I thought it was going to be a bigger deal! I'm glad they brought it to our attention.

**Comment by nutjob4life** [comment]
Thanks @KrisRecoveryDharma.

Update: as of _right now_ (see the time of this posting) I see the new `robots.txt` file is being circulated. We will need to wait a few days to see how this affects our SEO.

**Comment by KrisRecoveryDharma** [comment]
Thank you, Sean, for ensuring this issue has been fully documented.
Kris

**Comment by KrisRecoveryDharma** [comment]
Sean reported:

My results when searching "buddhist recovery" are:

* Standard browser, logged into [Google.com](http://google.com/): BRN, RR, RD
* Private browser on Google: BRN, RR, RD
* TOR browser via Russian proxy on Google: BRN, RR, RD
* Standard browser, DuckDuckGo: BRN, Online Recovery and Meditation Meetings, Buddhist Recovery Circle, RR, Buddhist * Recovery Eugene, Eight Step Recovery, RDO, etc. (in other words, we don't appear at all)
* TOR browser, DuckDuckGO: same as #4
* Standard Browser, Bing: similar to #4
* 
The results of tests 4, 5, and 6 may be because our robots.txt file was telling search engines to not index our site. We can wait for DuckDuckGo and Bing to come back around to see if our site is indexible or submit our sites to those engines.

**Comment by KrisRecoveryDharma** [comment]
Sean Suggested: 

We can get it higher. A good way is to have other sites link to us as much as possible. Tell your friends to write articles about us and link to [recoverydharma.org](http://recoverydharma.org/). Talk about it on your blog and link to [recoverydharma.org](http://recoverydharma.org/). Tweet about it and link it. Make Facebook postings that link it. Got a Tumblr? Make a post that links to it. Write some press releases and blanket news agencies with them and get them to write stories about us and link to us.

**Comment by KrisRecoveryDharma** [comment]
The issues is closed for the moment. 

Kris will bring the possibility of partnering with other organizations to the Communications Committee and to the Board.

**Comment by KrisRecoveryDharma** [comment]
Issue closed
