### ISSUE TITLE
ASAP Please: Take Down Summit buttons/links etc.

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#137]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ ] new content
- [ ] replacing existing content
- [X ] deleting content

Hey Tom, could you take down the pop up on the homepage, and the button that takes you to the Summit landing page.
On the landing page https://recoverydharma.org/2022-sangha-summit/
Can you please take down the Register and Scholarship buttons- thank you!!

**Comment by KrisRecoveryDharma** [comment]
WAIT!!!!!  That page has information that attendees need!!!

**Comment by KrisRecoveryDharma** [comment]
Rosana Dana says... nevermind!  I understand now
