### ISSUE TITLE
Website Developer Proposal - Review, Comment, Recommend

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#14]
The call has gone out,  35 proposals were received.  9 developers are shortlisted and their proposals are gathered. 

Website Team, Please review the proposals and give feedback. This includes follow up questions for the developers. 
Website team meeting during the week of 9/13/20 date tbd. 

Recommendations will be sent to the Board for their decision during their meeting on 9/24/20

Documents:

-  Web Development Report - outlines the process and summarizes the 9 proposals. https://docs.google.com/document/d/1AXRostfS99sz1Bg8tbm6IMzbOCuVfz9d3jRRHz4tdHI/edit?usp=sharing
 
- Web Developer Proposals Folder lists all of the proposals in detail
https://drive.google.com/drive/folders/18yAzoR-eoBrT0TZdkui6yxefqoN2IOI5?usp=sharing

- Scope of Work
https://docs.google.com/document/d/1vgIK-hz6wHgmhp6ReHZTtBqh3KU82DTymKcWhLLtkIo/edit?usp=sharing

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma I'm trying to access the second link "Web Developer Proposals Folder lists all of the proposals in detail" but when I log into Google Drive with `kelly@recoverydharma.org` I get "access denied". Can this be opened up? 🙏

**Comment by catpanclub** [comment]
> @KrisRecoveryDharma I'm trying to access the second link "Web Developer Proposals Folder lists all of the proposals in detail" but when I log into Google Drive with `kelly@recoverydharma.org` I get "access denied". Can this be opened up? 🙏

Same for me.

**Comment by KrisRecoveryDharma** [comment]
Sorry folks, I thought that the Website folder on the drive was public and accessible.  Dirk is working to reconfigure now. You should have access to the folder by this afternoon. 
Kris

**Comment by KrisRecoveryDharma** [comment]
I believe it is now available. Please confirm you can view it. 
https://drive.google.com/drive/folders/1HU7KdApv5IyUZ0V5h1kxKZV5fWTHrcBK
Kris

**Comment by KrisRecoveryDharma** [comment]
Evaluation Questions:
1. Does the proposal reflect that the developer listened to the needs and goals of RD?
2. Does the developer suggest any interesting, or unique solutions
3. Does the developer demonstrate capacity to deliver on promises?
4. Does the process meet our capacity to fulfill our part?
5. Inclusion, Diversity, Equity and Accessibility (IDEA)
6. Timeline and Cost

**Comment by KrisRecoveryDharma** [comment]
IT Committee reviewed proposals and made recommendations.  Firespring was recommended. Two others were alternates.  Other proposals were not recomended
