### ISSUE TITLE
New 2023 Elections page

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#147]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [x ] new content
- [ ] replacing existing content
- [ ] deleting content

Hi Tom, I sent you all the google docs so hopefully you're all set with permissions. This is the main page of info: https://docs.google.com/document/d/1yTkyg1gihAsp633dV5ZkJ83HDF7ITlK-r9TRsuJKIh4/edit

I'm wondering if this (2023 Elections) can go under News as a Bullet point? 
And then make another bullet point called Announcements that links to the news page?

**Comment by KrisRecoveryDharma** [comment]
Hey all,  Is it possible to have this simplified URL for the page? 
recoverydharma.org/election_2023
Thanks!

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @Lacey-boop Here is a draft of the page: https://recoverydharma.org/election-2023/. Let me know your thoughts and we can figure out menu structure/where this goes in the navigation.

**Comment by KrisRecoveryDharma** [comment]
Thank you so much!

So much right and correct about this page!
But to cut to the chase, here are the adjustments

*Election Landing Page*
<https://docs.google.com/document/d/1T54ZMD77u8mORxgXa4bInWLlcRbDyC8nt4bfV6XYBeY/edit>
I am seeing now that I made a mistake in labeling the documents.  The page
you created is part of this site, but it is actually a sub-page - the
Nomination Landing Page.  Here is the link to the central Election Landing
pag
<https://docs.google.com/document/d/1T54ZMD77u8mORxgXa4bInWLlcRbDyC8nt4bfV6XYBeY/edit>e
hub
landing page

*Job Description*
<https://docs.google.com/document/d/1T54ZMD77u8mORxgXa4bInWLlcRbDyC8nt4bfV6XYBeY/edit>
Can we make the Board Member Job description a page on the site too?

I have ideas to punch it up visually, but other than that, I have no other
suggested changes at this time.

Thank you!

Kris

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @Lacey-boop alright, I think I got all the pages created.

Link updated: https://recoverydharma.org/election-2023/ with new elections landing page which links to the new register to vote page and the nominations landing page, which links to the job description, candidate questionnaire and nomination form pages.

Let me know if everything looks ok, banner images can all be changed as well to differentiate, just wanted to get the pages created and content and forms all there.

**Comment by KrisRecoveryDharma** [comment]
Happy Dance!!! :-)

There are a few little things. I was going to go in to fix them myself, but
I don't seem to be able to get to the visual editor.

Here are the needed changes.


   - Header:  Get Ready for the 2023 Recovery Dharma Global Board Elections
   - 1st Paragraph:  Change the first sentence to:  "This is your page to
   links to the 2023 RDG Board Election...."
   - 1st Highlight Header:  Change to just "Nominate"
   - 2nd Highlight Header:  Change to just "Candidate Town Halls:
   - 2nd Highlight Link - link goes to the nomination form. It needs to go
   to the Candidate town hall page
   - 3rd Highlight: Volunteer with the Nominations Committee
   - Nominations Page: perfection!
   - Job Description Page  Align the headings to the left
   - Nomination Form:  The link to the Job description at the bottom of the
   page needs to go to: https://recoverydharma.org/board-jd/
   - Candidate Town Halls Page;  Don't see it.

If we have the capacity, it would be great to work on the visuals - Using
different colored dividing headers, etc.  If that is not possible, then the
corrections above should ensure that the content and the links are all
correct.

Wonderful as always!

Thank you!!!

Kris

**Comment by KrisRecoveryDharma** [comment]
Oops! Sorry,  Here's the link to the google doc for the Candidates Town
Hall page content

https://docs.google.com/document/d/1_rV9sXnGTLVmohERUTMDGibkevuUFEI_l1QicjRWfN0/edit

Thanks!

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @Lacey-boop Alright, I think we should be all good.

Visuals/photos and stuff aren't really my strong suit, but I can change some of the header photos to just be different than the blue/green gradient if that makes sense. If someone has time/energy to map out what should go where that would be a huge help!

**Comment by KrisRecoveryDharma** [comment]
Resolved
