### ISSUE TITLE
Bulk order info to Book Page

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#149]
Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ X] new content
- [ ] replacing existing content
- [ ] deleting content

On the book page https://recoverydharma.org/book/ in the first section with the icons, can you add a book icon with the title Bulk Purchases and have this info run with it: 
For information about bulk book purchases (50 books or more), please email info@recoverydharma.org and include the number of books you wish to purchase, your name, phone number, and shipping address.

thank you!

**Comment by tom-raley** [comment]
@Lacey-boop Hey Lacey, I made these changes and did my best with the grid format with an odd number of items. The longer description pushed some content around too. Feel free to reopen this issue if any other changes are needed!
