### ISSUE TITLE
Meeting resource links on "Find a Meeting" page aren't clearly links.

### ISSUE THREAD

**Issue by jerclarke** [RecoveryDharma/website#154]
## 📕 Summary

https://recoverydharma.org/find-a-meeting/

<img width="1348" alt="Screenshot 2023-02-04 at 3 00 29 PM" src="https://user-images.githubusercontent.com/139995/216789412-568414ff-9d7c-4b6e-985d-fa285e3e4dd4.png">

The headings in this section are links, but they don't look like links, which would mean making them green. 

Higher up on the same page are other column headers which are not links, further reducing the clarity that the second row of column headers are links. 

In the case of the "Add or Update a Meeting" header, this seems to be causing problems for those who manage the form, because they say they get a lot of email rather than people filling out the form. This was mentioned at the daylong retreat in Feb 2023 as a major problem for them. It seems like making these links really clear would help people find the links, especially for this form. 

Making the links be green text below the heading, the same way it's done for the "In-person Meetings" column above, seems like the way to go. Better for usability, and in the process better for accessibility.

Thank you for your service 🙏🏻

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @jerclarke This is a design question, as changing these would change them across the entire site. We could potentially make a custom box for these but that would require a larger discussion. I agree it's hard to tell these are links, but this is the design we went with. Happy to make whatever changes, but this is a much larger site-wide change than just these boxes most likely so wanted to open up a discussion.

**Comment by jerclarke** [comment]
IMO the design was a bad decision and should be changed, **BUT**:

You can fix this particular pain point without changing the design if you want, just duplicate the link below the heading: 

<img width="391" alt="updated meeting form widget" src="https://github.com/RecoveryDharma/website/assets/139995/9969e1ef-2b77-45ff-8b09-0854e3b7fcf0">

**Comment by KrisRecoveryDharma** [comment]
This is a content issue. The original was uploaded after a conversation and
decision from the RDO Sangha.

I agree about changing it. It is in the cue for the communicarions
committee to address.

**Comment by KrisRecoveryDharma** [comment]
Re-read the second suggestion.  Possible helpful ideas. It is in the
communications cue.

**Comment by unity1979** [comment]
Excellent feedback Jer. Some of us listened to your suggestion. See page again
