### ISSUE TITLE
Fix link to RDO-specific online meeting script to point to a generic one instead.

### ISSUE THREAD

**Issue by jerclarke** [RecoveryDharma/website#155]
I just noticed that the Online Meeting Script in this google drive that’s linked from the RD meeting resources pages is not the right one for the general public. It’s explicitly an [RDO](https://recoverydharma.online) document, with links to our safety guidelines and encouragement to donate to RDO. No one should use this but RDO.

[Meeting Materials Page](https://recoverydharma.org/resources/meeting-materials/)
[Basic Formats Google Drive that the page links to](https://drive.google.com/drive/folders/16bbNqbE87CogkDD94SQM6w_Ih07-PKGM)
[Faulty Online Meeting Script which is specific to RDO](https://docs.google.com/document/d/1tmAmdMp6Htj5gB8zUuYT-xl1BHgnz1CHJjSPD9k81i4/edit)

Instead of linking to an internal RDO script, the main RD site should use this generic version that I created just for this purpose:

http://bit.ly/rd-example-online-script

This script is a pair with a generic guide to hosting online meetings prepared by RDO and others in the community:

http://bit.ly/rd-zoom-meeting-setup-guide

They link back and forth to each other, and together constitute a pretty wholesome guide to online meetings. Previously the recoverydharma.org site linked to both documents on the COVID page, but I guess that link got lost in the process of the redesign. 

I think it would be best to link to both of these from the meeting resources page, but more than anything, I think it's vital that you not link to the RDO script, because it leads to confusion about RDO and RD and how they are related. 

One way to do it would be to just add a Google Drive shortcut to my documents into your Basic Formats drive, that way if I update them in the future based on changes to Zoom/RD, the changes will be reflected. 

Thank you for your work on the RD site 🙏🏻

http://bit.ly/rd-example-online-script

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @jerclarke Following up on this--I'm not following exactly what needs to be changed. Is it the script in the google drive? Or the link on the actual page? Let me know and I can try to make the changes. Sorry for the extreeeemely long delay.

**Comment by jerclarke** [comment]
The bug is that the **Basic formats** link goes to a Google Drive folder, and that folder contains a totally inappropriate online meeting script (because the script linked is for a specific community including a donate link):

<img width="823" alt="Screenshot 2023-06-11 at 10 20 16 AM" src="https://github.com/RecoveryDharma/website/assets/139995/7aacdba3-f327-4b90-8c23-f72ff89bd169">

There are various solutions available, but that is what absolutely needs to be fixed. 

Like I say above, there is an appropriate script that can be used instead, this one: 

http://bit.ly/rd-example-online-script

As the creator of both documents, it is that last link that should be shown to people interested in starting online meetings, not the one in the **Basic formats** directory currently. 

Hopefully that helps clarify, and re-reading my post above will make sense now. 

IMO What you should do:

* Update the https://recoverydharma.org/resources/meeting-materials/ page to have two sections instead of the **Basic Formats** one: A **In-person meetings** block and a **Online meetings** block. 
* The **In-Person meetings** block should link to the google drive you have now, but without the online meeting script in there. 
* The **Online Meetings** block should link to http://bit.ly/rd-zoom-meeting-setup-guide which both explains how to run an online meeting, and links to an example script people can use.

**Comment by unity1979** [comment]
I understand what you're saying. I was in the folders and just had a moment and decided it would be quick to replace the online meeting script with the one you mentioned Jer. 

Closing as resolved

<img width="702" alt="image" src="https://github.com/RecoveryDharma/website/assets/70724023/b1f3ab7f-2540-49a2-a302-17f1a292a3ed">
