### ISSUE TITLE
2023 Candidates Page

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#157]
# ✋ Hold it!

I can make edits once the page is up, but cannot do the setup
Kri

## 📕 Summary
- [X] New Content: Create a new page: https://recoverydharma.org/candidates-2023/
- [X] Update Content:   Add a highlight to the Election Landing Page: https://recoverydharma.org/election-2023/

## 🔍 Details

1. Create the following page:
https://docs.google.com/document/d/1_DxSQ9EN-mnkSxg0E1NRZb8ReAuMo2SuRxxzCeN9h7g/edit?usp=share_link

Update the Election Landing Page with this highlight: 

ICON:  Friends: https://drive.google.com/file/d/1kPsVo0FKvVuVpPCzV-Wpxff_Movk5CXL/view?usp=share_link
TITLE: 2023 Candidates
TEXT: See the list of 2023 candidates and review their candidate profile pages.

**Comment by tom-raley** [comment]
Here is a draft of the page, sorry for the delay! Let me know your thoughts and any change requests.

https://recoverydharma.org/2023-rdg-board-candidate-summary-page/

**Comment by KrisRecoveryDharma** [comment]
Thank you!

Do you want me to do the resizing of the pictures so that they are all
square?
I don't have fancy programs, so I'd just have to do it by hand and by-eye

I will run this by others for review and schedule its publication with
Lacey.

There are 4 more who have said yes and who committed to completing a
questionnaire.

Thanks!

Kris

**Comment by KrisRecoveryDharma** [comment]
Here is the next profile for upload:  Candidate Valentine

https://docs.google.com/document/d/1yHxItesXBaKthnuk2rr3EwBRu91H0nfzwz1Q7o3Nh74/edit?usp=sharing

**Comment by tom-raley** [comment]
@KrisRecoveryDharma Updated! Heads up--Valentine's picture is too small. Has to be at least 300 x 300 I think to fit properly. Larger the better as long as it's square 😄

**Comment by KrisRecoveryDharma** [comment]
New Summary!
Lauren Ero. 
This time I have just left the picture file in the document untouched.  It may be a little tight. 
https://docs.google.com/document/d/1ZdUg6ep1xI0wv1JraFCrW_YnVq5TWrpoDDS4ZOgllok/edit?usp=sharing

**Comment by tom-raley** [comment]
Updated! Picture worked out great.

**Comment by KrisRecoveryDharma** [comment]
Candiate Summary for John Mullenix

2023 Candidate Summary – John Mullenix 

https://docs.google.com/document/d/1TJVZMUy-Mmn15-CryPW3_UL4yi-0eQmMLpX8Sn26ArY/edit?usp=sharing

**Comment by KrisRecoveryDharma** [comment]
Josh Rychert new picture

https://drive.google.com/file/d/1R-mYdmodzTqxVj52stE-Zi3J_-RWfH0Y/view?usp=share_link

**Comment by KrisRecoveryDharma** [comment]
Regional Map

I'm feeling stuck on where to put it or how to format it to make it look good, but it needs to go onto the Candidate Summary Page.   Thank you for any assistance and wisdom you can provide. Maybe it needs its own orange section?

https://drive.google.com/file/d/1mmdwVSDqspFucEf3DewmvVskWmnE2cUz/view?usp=share_link

**Comment by tom-raley** [comment]
@KrisRecoveryDharma Updated page with John Mullenix. Would it possibly make sense to have the map in a popup as well with a button saying Click Here to See Regional Election Map or something like that? It doesn't look great having the image on the page by itself, as it's pretty large and detracts from the candidate profiles I think. Let me know your thoughts.

**Comment by KrisRecoveryDharma** [comment]
A pop-up sounds perfect!

**Comment by KrisRecoveryDharma** [comment]
Link it to the narrative in the introduction.

**Comment by tom-raley** [comment]
Done, let me know your thoughts.

**Comment by KrisRecoveryDharma** [comment]
Profile - Troy Van Denover

https://docs.google.com/document/d/1Bqmborwmboz6vXKslwiM9L3kXsvmJleOrd2B9njpwoQ/edit?usp=sharing

Thanks!

**Comment by KrisRecoveryDharma** [comment]
Oh!  And the map is perfect!

**Comment by KrisRecoveryDharma** [comment]
Another Candidate Profile

Natalya Fearnley
https://docs.google.com/document/d/1wQyJkr0bUvYBTUJZ4u8r9yIKyPStR13dOHDUmYHC4kc/edit?usp=sharing

**Comment by tom-raley** [comment]
Natalya has been added!

**Comment by KrisRecoveryDharma** [comment]
Profile for Shad Graham
https://docs.google.com/document/d/1hoT4JazG0_v1thXQkkk6Mi9CuqPPhrEENxGhcRAlngo/edit?usp=sharing

**Comment by KrisRecoveryDharma** [comment]
Profile for Bryant Belarmino!
https://docs.google.com/document/d/1hM0By5v_5G342SIpvobq1-QjV5HKMyMITpipNsYkJmI/edit?usp=sharing

**Comment by tom-raley** [comment]
Bryant and Shad are updated!

**Comment by KrisRecoveryDharma** [comment]
Profile for Thomas Tran
https://docs.google.com/document/d/1YjG1vL_EHsHwhOSe9yW8qq3DOM8Ll8NgOskb39yfToM/edit?usp=sharing

**Comment by KrisRecoveryDharma** [comment]
Profile for Jon Blase
https://docs.google.com/document/d/1q_8zB-5Qpe0u12S6n0f-mTtlApNjrCdKsIYehGXaMnc/edit?usp=sharing

**Comment by KrisRecoveryDharma** [comment]
Profile for Madi Nitzki
https://docs.google.com/document/d/1FzYwWoZucnLH3nMoFeojUe7LW52SCCzXojkE98-raQw/edit?usp=sharing

**Comment by KrisRecoveryDharma** [comment]
All profiles have been added.
