### ISSUE TITLE
Buddhist Recovery research survey

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#158]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ X] new content
- [ ] replacing existing content
- [ ] deleting content

https://recoverydharma.org/blog/

Could you add a post about the Buddhist Recovery research survey (I sent it to you via a doc in gmail)

thank you as always!

**Comment by tom-raley** [comment]
Posted! Sorry for the delay!
