### ISSUE TITLE
Small change to Town Hall page

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#163]
Hey Tom (or Kris? Not sure who put this together), 
sorry I'm just seeing this now.
https://recoverydharma.org/town-halls-2023/

At the bottom of the page, could you get rid of that random green rectangle that appears on the left.

And the 2 colored blocks at the bottom of the page- can we get rid of the color and just make the copy black?
I think it's a bit hard to read otherwise (especially for people with color blindness)

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @Lacey-boop I think this is closed? I didn't address it, so maybe Kris did? Not sure.

**Comment by KrisRecoveryDharma** [comment]
Sorry, forgot to close it here. 
Thanks!
Kris
