### ISSUE TITLE
Contribute / Donation page: Amazon Smile sunsetted—references & links should be removed 🐛bug

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#165]
Hello Friends

## 🐛 Describe the Bug

Apparently Amazon Smile has sunsetted their program on Feb 20, 2023. So the Shop with amazon smile button brings us to a "AmazonSmile Is Ending" page. 

Consider removing Amazon Smile references.

## 📜 How To Reproduce

1. Go to https://recoverydharma.org/contribute/
2. Below Shop Amazon Smile, click on Donate Now
3. Notice we are at a page that says Amazon Smile has ended. 
100% reproducible

## 🔎 Expected Behavior

Normally the page would say, ...your donation charity will now go to Recovery Dharma Inc!

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/70724023/227265630-778f58c4-b3c9-4def-8562-e9f64cc7e3f2.png)

![image](https://user-images.githubusercontent.com/70724023/227265678-2546a91e-d20f-4ede-9c45-d0e12048e78c.png)

**Comment by KrisRecoveryDharma** [comment]
Resolved
