### ISSUE TITLE
Need resume connected to a button

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#167]
https://recoverydharma.org/2023-rdg-board-candidate-summary-page/#:~:text=Web%20Design%20Company-,Tracie%20Story,-VIEW%20SERVICE%20RESUME

Candidate Summary Page
Tracie Story Pop-Up. 

I don't know how to save the resume document so that the link on the button goes to an online document. 

Tom, please take the document that is linked under the button and use your magic to attach it to the resume button. 

Thank you!

Hope you are getting some sleep!

Kris

**Comment by tom-raley** [comment]
@KrisRecoveryDharma So sorry I missed this!! Is it still needed?

**Comment by KrisRecoveryDharma** [comment]
Hmmm
I'm not sure

**Comment by KrisRecoveryDharma** [comment]
Yes, it is still needed

**Comment by tom-raley** [comment]
It looks like the candidate summary page has been made private and isn't currently published. I'm going to hold off on this, can you provide some clarity on what is needed where? This seems related to the candidate profiles for the election which is now over but I could be wrong 😄
