### ISSUE TITLE
082120 Board Minutes

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#17]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [X ] new content

## 🔍 Details

Please upload latest 082120 minutes to https://recoverydharma.org/about-our-nonprofit-
[08212020 Minutes- BoD Meeting .pdf](https://github.com/RecoveryDharma/website/files/5226198/08212020.Minutes-.BoD.Meeting.pdf)

**Comment by nutjob4life** [comment]
In progress

**Comment by nutjob4life** [comment]
File uploaded and hyperlink installed on https://recoverydharma.org/about-our-nonprofit

If this looks okay @Lacey-boop please go ahead and close this issue. If not, add a comment and let me know what else to fix! 👍

**Comment by nutjob4life** [comment]
Thanks for the ♥️ @Lacey-boop!
