### ISSUE TITLE
Summit button for homepage

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#171]
- [X ] new content
- [ ] replacing existing content
- [ ] deleting content

Hi Tom! Can you create a Sangha Summit page for the homepage that leads to the summit page like you did last year? 
https://recoverydharma.org/2023sanghasummit/

thank you!!

**Comment by tom-raley** [comment]
@Lacey-boop Sorry, out of the country currently with limited computer/internet access, but just added it! Let me know if it all looks good.
