### ISSUE TITLE
Summit Livestream ticket widget

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#173]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ X] new content
- [ ] replacing existing content
- [ ] deleting content

Hi Tom! I'm not sure what this will look like but maybe you can make a button under the Register Here! Button. The new button can say "Summit Livestream". Can you change the Register Here button to say " In-Person Registration"

<div style="width:100%; text-align:left;">   <div id="simpletixEmbed">       <script src="https://embed.prod.simpletix.com/assets/widget/embediFrame.js" data-url="https://embed.prod.simpletix.com/58b00f8d-4bcc-4b9b-90b9-34e2a39ac136/138844?smtxorigin=12"></script>   </div>   <div style="font-family:Helvetica, Arial; font-size:12px; padding:10px 0 5px; margin:2px; width:100%; text-align:left;" >       <a style="color: #ADB0B6; text-decoration: none;" target="_parent"        href ='[https://www.simpletix.com/?utm_source=embed%26utm_medium=web%26utm_campaign=embedwidget%26utm_content=footer%26a=logo'](https://www.simpletix.com/?utm_source=embed%26utm_medium=web%26utm_campaign=embedwidget%26utm_content=footer%26a=logo%27)>Powered by SimpleTix</a>   </div></div>

thank you!

**Comment by Lacey-boop** [comment]
Oh and could you make a third button that says: Annual Meeting Zoom
with this link
https://us02web.zoom.us/j/83380790245?pwd=ZTBoY1VwMDZ1WHlzbEhSNnEwTjdVZz09

**Comment by tom-raley** [comment]
Hey @Lacey-boop should be all set. I think the simpletix embed script above is missing some additional code, so I couldn't get it to load like a popup like the in-person registration link, but it directs to a new tab for now. If you see any additional code where you got the embed from or have a link to it, I can take a look. But at least people can access it.
