### ISSUE TITLE
for ASAP: New Tab under "Resources"

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#174]
Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ X] new content
- [ ] replacing existing content
- [ ] deleting content

Under "Resources" could you create a new page called "RD icons"

and add these downloadable PNGs to the top of the page

![RD-triangles-color](https://github.com/RecoveryDharma/website/assets/70229948/59a8a866-3063-4506-929a-81dc5de30005)
![RDcolumns-color](https://github.com/RecoveryDharma/website/assets/70229948/33979591-8104-47f3-b5aa-6841cf8fcb66)
![RC-circle-black](https://github.com/RecoveryDharma/website/assets/70229948/6d0cb31d-acdb-431b-9057-1426c5900ff4)
![RD](https://github.com/RecoveryDharma/website/assets/70229948/0e48a7e1-a596-4e7e-aa40-cb24fcc78f7a)
![RC-circle-color](https://github.com/RecoveryDharma/website/assets/70229948/22ea8107-66b7-4f56-bebe-b43bf4180036)

And then include this image of the book:
[rdbookcover-finalfinal.pdf](https://github.com/RecoveryDharma/website/files/12175979/rdbookcover-finalfinal.pdf)

with this explanation under it: 
https://docs.google.com/document/d/1u5S7-RfMDAQJ7fmbnoJVCDEViqyUitFuRGCcFziWGj4/edit

thank you!

**Comment by jerclarke** [comment]
Wow. Is this an official logo for RD? Please change the font if you're going to go with that icon, they are a very distracting combination of stark, aggressive letterforms with a floppy icon.

**Comment by tom-raley** [comment]
All set. New page is here: https://recoverydharma.org/resources/rd-icons/ and also under the Resources menu tab. Let me know if there's any changes needed!
