### ISSUE TITLE
Update About Page

### ISSUE THREAD

**Issue by randallwesleyhall** [RecoveryDharma/website#179]
Hi, on the [About page](https://recoverydharma.org/about/), please remove Jeanette Castaneda, and change "Board Member" to the following descriptors for these board members:

Natalya Fearnley - President
Thomas Tran - Vice President
Lauren Ero - Registrar
Cherri Hendricks Hostetler - Treasurer

Thank you!

**Comment by tom-raley** [comment]
@randallwesleyhall should be all set!
