### ISSUE TITLE
Reconfigure Meetings Page to move content up toward the top

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#18]
https://recoverydharma.org/meeting-list

Move the two sections, Stay Connected" and "About Meeting List Process,"  From the bottom of the left column to the bottom of the right column (Under "Start a New meeting." The goal is to bring these two sections "above the fold"  so that that they are seen with the other content without scrolling

![image](https://user-images.githubusercontent.com/70176719/94097958-8cd7f700-fdf5-11ea-93ba-eb9a0c442f85.png)

from

**Comment by nutjob4life** [comment]
Hi @KrisRecoveryDharma! I moved the bottom two sections to the right column. Please view it at https://recoverydharma.org/meeting-list or view this screenshot:

![Screen Shot 2020-09-24 at 9 12 55 AM](https://user-images.githubusercontent.com/814813/94156905-38a93300-fe46-11ea-8a61-f3d4e3ec79dc.png)

If this looks okay, please go ahead and leave a comment saying so and click "Close with comment". If not, add a comment saying what else you'd like change and just click "Comment".

**Comment by KrisRecoveryDharma** [comment]
Perfect! 
It is Complete.
Thank you!
Kris
