### ISSUE TITLE
Please update Nav Menu Bar

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#180]
I have WordPress access, but I'm not sure how the Nav Menu Bar is stored. (Tom, could you point me in the right direction? Is it in a plug-in or somewhere else? Thanks in advance.)

1. Please remove 2023 Sangha Summit from Meetings & Events
<img width="247" alt="image" src="https://github.com/RecoveryDharma/website/assets/70724023/9c8587f5-29d0-4acb-94ac-bd18b6ca7520">

2. Please update the [Meetings & Events] Link to go directly to Find-A-Meeting
URL: http://recoverydharma.org/find-a-meeting/
<img width="197" alt="image" src="https://github.com/RecoveryDharma/website/assets/70724023/60e4ac98-ccc3-4a7d-a025-c93adc976d0e">

3. In News, please remove the "Announcements" dropdown choice, so that it just says News (without a dropdown). The result should look similar to the Home menu
<img width="203" alt="image" src="https://github.com/RecoveryDharma/website/assets/70724023/db5bdc84-c856-4106-a7a0-b273c7d8ffce">
(Home menu)
<img width="82" alt="image" src="https://github.com/RecoveryDharma/website/assets/70724023/f5f78a13-a502-4e76-89a9-7aaee8ab20d4">

4. Please remove the "HOME" menu — it's redundant because clicking on "Recovery Dharma Global" logo takes us back to www.recoverydharma.org/
<img width="461" alt="image" src="https://github.com/RecoveryDharma/website/assets/70724023/b6abbf64-ee16-414f-9bef-5ab3507ec4f0">

5. Please replace the "GET STARTED" link so the URL points to the same thing as Beginners Guide:
URL: https://recoverydharma.org/get-started/beginners/
<img width="141" alt="image" src="https://github.com/RecoveryDharma/website/assets/70724023/1ae4d56f-812e-4716-9788-a0ff5009b107">

6. Please swap the positions of [Meetings & Events] with [Resources] such that Resources is on the left and Meetings & Events is on the right. So it looks like this:
![image](https://github.com/RecoveryDharma/website/assets/70724023/44b5f23d-a5b6-47f7-bd34-8185ba886331)

Thanks so much. Feel free to ask for clarification.

**Comment by KrisRecoveryDharma** [comment]
Hello Thomas,  has this gone through the communications committee?
