### ISSUE TITLE
Book page is totally broken

### ISSUE THREAD

**Issue by jerclarke** [RecoveryDharma/website#181]
## 🐛 Describe the Bug

The /book/ page is missing all images and colors, and the top menu is duplicated in an endless white void. 

This has happened before, so I imagine the previous fix will fix it again. 

## 📜 How To Reproduce

https://recoverydharma.org/book/

Tested on Safari and Chrome on macOS.

## 🖼 Screenshots

<img width="1229" alt="Screenshot 2024-01-10 at 1 17 13 PM" src="https://github.com/RecoveryDharma/website/assets/139995/d24d1fc8-430f-4bca-bdba-7a1cd8ed1fe3">

**Comment by tom-raley** [comment]
@jerclarke @KrisRecoveryDharma @Lacey-boop This happens periodically and I have no idea how to fix it or why it happens. I also don't have access to the logs, only firespring (who built the site) does. They're really the only ones who could troubleshoot this unless they give us access to the logs.

I'm not sure who our contact is there now, but I'd be happy to reach out if we still have one.

It also appears to be fixed now, it always resolves itself after a period of time, but when it happens the site is almost unusable for however long it lasts :(
