### ISSUE TITLE
Email Sign-Up Problem on Home Page

### ISSUE THREAD

**Issue by randallwesleyhall** [RecoveryDharma/website#183]
When someone tries to sign up for the newsletter by using the field at the bottom of the homepage, as soon as they type their name in the field, the "sign up" button disappears.

**Comment by tom-raley** [comment]
Hi @randallwesleyhall --I'm not able to reproduce this issue on my end. Do you have any other info ie. what browser this happens in or a screen recording of it happening? Any extra info would be great, thanks!

**Comment by randallwesleyhall** [comment]
It is happening to me on chrome but not safari. A member reported it as well, but not sure what she was using. As soon as you start to type your email adddress on chrome, the sign up button disappears. On Jan 13, 2024, at 7:55 PM, Tom Raley ***@***.***> wrote:﻿
Hi @randallwesleyhall --I'm not able to reproduce this issue on my end. Do you have any other info ie. what browser this happens in or a screen recording of it happening? Any extra info would be great, thanks!

**Comment by tom-raley** [comment]
@randallwesleyhall Ok, I have tried it in Arc Browser, Chrome, Safari and Firefox and cannot get the sign up button to disappear. If you have a screen recording of it happening or something or if anyone else is able to reproduce that would be super helpful! Otherwise, it's very hard to troubleshoot.

**Comment by randallwesleyhall** [comment]
It seems to be working again. That was very strange. Thank you for checking it out.On Jan 15, 2024, at 7:50 AM, Tom Raley ***@***.***> wrote:﻿
@randallwesleyhall Ok, I have tried it in Arc Browser, Chrome, Safari and Firefox and cannot get the sign up button to disappear. If you have a screen recording of it happening or something or if anyone else is able to reproduce that would be super helpful! Otherwise, it's very hard to troubleshoot.
