### ISSUE TITLE
91320 meeting minutes

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#19]
## 📕 Summary

Please add 09132020 minutes to this page:
[20200913 Minutes- BoD Meeting .pdf](https://github.com/RecoveryDharma/website/files/5284467/20200913.Minutes-.BoD.Meeting.pdf)

thanks!

**Comment by nutjob4life** [comment]
Assuming the target page is: https://recoverydharma.org/about-our-nonprofit

It doesn't hurt to mention this when submitting, though!

**Comment by nutjob4life** [comment]
Uploaded PDF attachment and added an extra link to https://recoverydharma.org/about-our-nonprofit

In the future, we may want to think of a better way to present this information. The page is looking funny and unbalanced currently.

![Screen Shot 2020-09-25 at 4 26 43 PM](https://user-images.githubusercontent.com/814813/94317481-0d107080-ff4c-11ea-9193-e6388a1cec0b.png)
