### ISSUE TITLE
Links to "Affinity list" on Diversity and Accessibility page are all broken

### ISSUE THREAD

**Issue by jerclarke** [RecoveryDharma/website#191]
## 🐛 Describe the Bug

https://recoverydharma.org/resources/diversity-accessibility/

All the Affinity list links lead to 404 errors. Not sure if it's a different link now or what, but we should probably fix it. 

Might also be good to just have the link once at the top, rather than replicating it in each section. 

## 📜 How To Reproduce

Put steps to reproduce the behavior here, **including URLs**, such as
1. Go to https://recoverydharma.org/resources/diversity-accessibility/
2. Click on "Affinity list" in any of the sub-group sections
3. 404 error

**Comment by tom-raley** [comment]
This should be fixed. Feel free to reopen if I missed any.
