### ISSUE TITLE
Update Link to Bylaws

### ISSUE THREAD

**Issue by randallwesleyhall** [RecoveryDharma/website#192]
At the bottom of the About page (https://recoverydharma.org/about/), there is a link to the Bylaws. It needs to be updated to link to:

https://drive.google.com/file/d/1RI4wGEQmrdkodRs70idCOuPmsxHCU3rW/view?usp=drive_link

Thanks!

In service,
Randy

**Comment by KrisRecoveryDharma** [comment]
That was an intentional decision of the committee who originally built the
site.  I think there us a good argument for changing it.  But just know
that it would be a content change rather than a typo correction.

**Comment by KrisRecoveryDharma** [comment]
Before all the content was receny changed, the first section of the About
page had the list of links ylto all the important documents: Bylaws,
minutes, financial reports etc.

That section was recently moved to the bottom of the page with new icons.

**Comment by randallwesleyhall** [comment]
Hi Kris, I am not sure I understand your comment. The Board amended the Bylaws at the meeting last Sunday and I am simply asking that the amended bylaws be linked instead of the now outdated ones. No content is being changed.

**Comment by KrisRecoveryDharma** [comment]
Ah,  sorry,  I also had a lot of typos.

The link at the bottom of the site was originally designed to stay
constant, with the specific link to the specific document found on the
About page.

**Comment by randallwesleyhall** [comment]
This still needs to be updated, thank you
