### ISSUE TITLE
Post Minutes

### ISSUE THREAD

**Issue by nutjob4life** [RecoveryDharma/website#2]
(Via email from lacey@recoverydharma.org)

## 📕 Summary

Post two sets of minutes (attached).

## 🔍 Details

Probably to this page: https://recoverydharma.org/about-our-nonprofit ❓❓❓

## 📈 Attachments

- [_082020 Minutes- BoD Meeting .pdf](https://github.com/RecoveryDharma/website/files/5120402/_082020.Minutes-.BoD.Meeting.pdf)
- [2020 Annual Board Meeting minutes .pdf](https://github.com/RecoveryDharma/website/files/5120403/2020.Annual.Board.Meeting.minutes.pdf)

**Comment by Lacey-boop** [comment]
Yes under Minutes section thank you!

**Comment by nutjob4life** [comment]
Both posted under Minutes; see the newly updated page at https://recoverydharma.org/about-our-nonprofit

**Comment by KrisRecoveryDharma** [comment]
The menu looks great! Thank you.  Now, the next thing is to adjust the text of the Meeting page.  My brain is working a lot better this evening. I will send you the text.
