### ISSUE TITLE
Update all Meeting links to Non-tabbed version of link

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#20]
[X] replacing existing content

## 🔍 Details

We need to (A) all these links to map to (B) new links, as mentioned below this image 🙏:
![image](https://user-images.githubusercontent.com/70724023/94495932-e0589500-01a7-11eb-8fc1-069d90a9bbce.png) 

Tab/Time Zone Name | Published HTML Link:
-- | --
In Person | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1492891510&single=true
Hawaii | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=188599084&single=true
Pacific US | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=496973103&single=true
Mountain US | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1567715471&single=true
Central US | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1870057131&single=true
Eastern US | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1997228258&single=true
Atlantic | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=862403844&single=true
UK | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1799102808&single=true
Central Europe | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1971437393&single=true
Nepal | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=2113693318&single=true
Japan | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1497061528&single=true
Australia East | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=1833391122&single=true
N Zealand | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=2131795796&single=true
Women / Nonbinary | https://docs.google.com/spreadsheets/d/e/2PACX-1vQmuN3eHggYoR9maoLttce3MkZLTZ0UTByIv_lKK7MbXEElHMBCwD_HX8aP3d1Tcp-J7TihbPgatLWL/pubhtml?gid=5118134&single=true

(originally https://github.com/RecoveryDharma/Meetings/issues/5 )

**Comment by nutjob4life** [comment]
Updated the page at https://recoverydharma.org/meeting-list and the "Meetings" mega-menu.

Please note that menu changes are heavily cached and may not appear for everyone right away. Just be patient! ⏳

Hope these links stabilize soon! 😯
