### ISSUE TITLE
Need to add more columns to meeting list spread sheet

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#23]
Hey Meeting List Team,

I just received a stark awakening this week.  We were informed that the calendar plugin that they are using for the new website does not have the capacity to sort tags in a way that we are accustomed to.  I am experiencing quite the arising of quite the combination of emotions as the reality of it sets in.  Self-doubt that my repeated notes on this were not effectively communicated, frustration at the drop in communication, distrust in Firesprings honesty and Anxiety about the potential consequences and repercussions for our community. 

I am sure we will be able to come up with some solution. All of you tech folks have taught me that. However, this has caused me to realize that our sorting fields have gotten lost in the fray as we strove for the time zone conversion feature.  I would like to re-insert and re-assert them in our process. I would like to make sure that these fields are available somewhere in our database.  Since we are getting busy updating our existing spreadsheet I would like to add these fields. We may not display all of them in the tabs, but I want to make sure they do not get lost.

I would like to add the following fields to the spreadsheet: 

* Sangha:  (Fill-in)  (A group of people who organize meetings together)
* Inter-Sangha (Fillin) (A Network of independent Sanghas/Groups that pool their resources)
* Type:  (In-Person, Online, Hybrid)
* Format: (Discussion, Speaker, Inquiry, Literature, Sit and Share, Silent Sit) 
* Affinity (BIPOC, LGBTQIA+, Women, Gender Expansive, Men)
* Topics (General, Food, Codependency, 

This list was easy for me to re-create this morning because I have re-written it many times in this process.  

This is all information that we were going to to have to collect this month anyway. We are just starting with our own spreadsheet first. Perhaps it is time for us to create a new google form and ask members to start in on the process we anticipated - starting to enter their information into the form anew. 

I'll be at home all day today working on the home page and other aspects of the Website. 

Thanks for all of the work that you do,

Kris

**Comment by unity1979** [comment]
More Topics in addition to: General, Food, Codependency, 
Mental Health, Food, Gambling/Debt, Love/Intimacy, Porn/Sex, Trauma/PTSD, Self-Harm, Shopping/Spending, Social Media/Technology, Substances (Alcohol, Drugs, Prescriptions, etc)

**Comment by unity1979** [comment]
Codependency, Food, General, 
Mental Health, Money (Debt/Shopping), Relationships (Love/Intimacy, Porn/Sex) Trauma/PTSD, Self-Harm, Technology(Social Media/Gaming/TV), Substances (Alcohol, Drugs, Prescriptions, etc)

**Comment by KrisRecoveryDharma** [comment]
This issue has replaced by work with Firespring on new CSV file.
