### ISSUE TITLE
Sangha Summit Announcement for the Bulletins

### ISSUE THREAD

**Issue by joelro87** [RecoveryDharma/website#24]
Hi, 

I would like to add this announcement to the website. 

Thanks,
Joel 

https://docs.google.com/document/d/1Dz9p4dHME2NOBnLYggF6_JSgKQ9mf6B1izflo5RWfQU/edit

**Comment by nutjob4life** [comment]
Posted; see permanlink: https://recoverydharma.org/requesting-bids-for-the-2021-sangha-summit

I went ahead and made some minor edits (2020→2021, changing hyphens to en-dashes for ranges, using bullet lists, etc). If I missed any problems, please re-open the issue with a comment.
