### ISSUE TITLE
President's Town Hall post on Bulletin

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#25]
## 📕 Summary

New Content:  Bulletin Announcement for President's Townhall on 10/24/20
https://recoverydharma.org/bulletins
## 🔍 Details

Replace this with detailed information about the request. For new content, make sure to mention
- Join us for the President's Townhall!
- Describes the content of the event, date & time and includes a join now link. 
- Bulletin
- How it should be hyperlinked from existing pages - Not sure how to answer this question.

## 📈 Attachments
Here is the whole article: We want it posted as an article on the site (Not a link to the google doc)
https://recoverydharma.org/bulletinshttps://docs.google.com/document/d/1jsMJGjP-IhFiLj_yx2n6RjPT6iFc-e6BiadL6jjOtfM/edit?usp=sharing

Thank you!

**Comment by nutjob4life** [comment]
Posted to bulletins; permanlink: https://recoverydharma.org/presidents-town-hall

Need any changes? Feel free to comment. If not, please go ahead and click "Close".

**Comment by nutjob4life** [comment]
Closing this issue; the town hall on 2020-10-24 has passed
