### ISSUE TITLE
Need to redirect web address for meeting updates that still exist for the "Old" form

### ISSUE THREAD

**Issue by ctwilkie** [RecoveryDharma/website#26]
The link: https://recoverydharma.org/meeting-list-request is still active. I've seen it linked on other non RD owned website "RD Friends act" for example.

We need to either redirect this link to:
New form:
https://docs.google.com/forms/d/e/1FAIpQLSf0LLyvNdQhwE6FHtI_V6IJ7EOpWKlx8y_sIQrgV1wuivrlzQ/viewform

Or Delete this link in general while we update the website.

**Comment by KrisRecoveryDharma** [comment]
I vote for a redirect to the current meetings page.

**Comment by nutjob4life** [comment]
Form: disabled ❌
Page containing form: trashed 🗑
Redirect to `/meeting-list`: installed 🔀
Ticket: closed 📪

Feel free to "reopen with comment" if this doesn't meet your expectations 😉
