### ISSUE TITLE
Reduce PDFs on new site but keep things printable

### ISSUE THREAD

**Issue by nutjob4life** [RecoveryDharma/website#27]
## 🤔 Tell Us About the Feature

Currently, `recoverydharma.org` has _way too many PDFs_. This makes sense because people wrote meditations, community guides, scripts, etc., using Micro$oft Word or Google Docs and just ran off a PDF to posting and printing.

But a preponderance of PDFs poses a usability challenge, especially on mobile (where over half of all browsing occurs). Ideally, we'd like to have fewer PDFs. For example, the First Foundation of Mindfulness meditation should be just a single HTML page that you can navigate to, search for, etc. We will also have different versions of pages, such as "Long Form of the Practice" and "Quick and Efficient Practice" to support. And as a bonus, it'd be great to have versions of "With Commentary" and "Without". All this should be doable—maybe with some extra plug-ins.

**However**, a lot of in-person meetings _print this stuff out_, so using the File → Print function on a browser still needs to work with:

- Decent margins
- No background graphics
- Good readability

Lots of websites (think recipe or cooking sites) support this with enough CSS that tell how to render a `@media` for printing. Does WordPress—or more specifically—does our _next release of WordPress with [Firespring](https://firespring.com)_ support it?

## 🎇 What Solution You'd Like

- [x] Ensure @tom-raley has access to new site
- [ ] Extract a PDF and convert to plain HTML for display on WordPress
- [ ] Print the WordPress page to see if it still looks nice, adjusting settings as necessary
- [ ] Optionally see if Firespring or other Plug-in can help
- [ ] If it works

## 〽️ Alternative Ideas

If this doesn't work out, we will need to start uploading all 4017 PDFs (okay, not that many) from the current `recoverydharma.org` to the new Firespring site.

**Comment by KrisRecoveryDharma** [comment]
I support this idea. Go for it!
Kris

**Comment by tom-raley** [comment]
@nutjob4life I don't believe I have access to the Wordpress site. I have some good tools to convert PDF to HTML, so once I get access to the files I can start turning the PDFs into pages and work on the printing aspect!

**Comment by nutjob4life** [comment]
@tom-raley check your [email](mailto:tom.raley@gmail.com) for activation links for the [old site](https://recoverydharma.org/) and the [new site](http://recovery-dharma.flywheelsites.com/).

Note that for the new site, it's guarded behind an HTTP Basic auth challenge. You'll need the username and password for _that_ as well. I'll send you those using another medium.

**Comment by KrisRecoveryDharma** [comment]
Checking on the status of this project.  
How's it going? 
Thanks for your work!
Kris

**Comment by tom-raley** [comment]
@KrisRecoveryDharma Ive just about got all of the meditations done. Haven’t had much time this weekend so far, hoping to finish the other PDFs Monday or Tuesday.

**Comment by KrisRecoveryDharma** [comment]
List of pages to be created by RDG in concert with Firespring

Book
IDEA
The Practice
Truth
Eightfold
Meditation
Core-Intentions
Dedication
Format

**Comment by KrisRecoveryDharma** [comment]
Request:  Use templates within the Portfolio Section
Portfolio
   Project Category
       Category
          Examples

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @nutjob4life I have all the meditations and meeting materials converted over from PDFs to pages now and the printing is looking pretty good. You can check out the progress at http://recovery-dharma.flywheelsites.com/resources/

How deep do we want to go--ie should the book be its own page (I'm thinking not)? And as far as flyers and pamphlets, I'm thinking those should also remain in doc/PDF format so people can print them properly and customize. Let me know your thoughts.

**Comment by KrisRecoveryDharma** [comment]
This is spectacular! Thank you!!!!!!
<<Communications Committee Chair Happy Dance!>>

This is so helpful.  It is wonderful progress!
I do have a few adjustments, but now we can have a look at this and move
forward.

Thank you than you thank you!

Let me know if you would like to chat by phone / Zoom or you would like me
to just list my next steps here.  I would prefer to chat by phone because I
am not 100% confident in my suggestions and would love to talk them through
with you.

Thanks again,

Kris

**Comment by tom-raley** [comment]
@KrisRecoveryDharma Thanks!! I’d love to hear your thoughts, I’m pretty open today and tomorrow, let’s try and do a zoom call. Only time I can’t do is 10:30-11:30 eastern.

**Comment by KrisRecoveryDharma** [comment]
Hi Tom R,
My work week got a way from me. 
Let's try for Friday afternoon. 
Are you available then? 
Kris

**Comment by tom-raley** [comment]
Hey @KrisRecoveryDharma! Yes, only time I can’t do is 4-5p eastern. Can we shoot for 1 or 2p eastern?

**Comment by KrisRecoveryDharma** [comment]
This is our lingering question that is website policy level discussion.  

My concern is around the monthly board minutes - especially since each month's minutes are essentially a packet of 10 different documents. 

Let's plan on this being our primary policy discussion over the next couple of weeks. 

Thanks to all!

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @Lacey-boop I think this issue is resolved for the most part? I think the new website contains many less PDFs and most content is either printable as a google doc, or as HTML on the site. Let me know if there's any reason to leave this open.

**Comment by KrisRecoveryDharma** [comment]
3-2-1-0 
When I close this Git Hub, there will be ZERO issues listed! 
I'm sure it is very temporary, but it feel very good at midnight the night before the launch

GOOOOOOO T.E.A.M!!!!  <3 <3 <3 <3
