### ISSUE TITLE
Bid Requirement Update 

### ISSUE THREAD

**Issue by joelro87** [RecoveryDharma/website#28]
Update to Bid Requirements Bulletin
 
We are wanting to add a piece about diversity and accessibility to the bid requirements. 
 
"Accessibility and Inclusion: All venues need to be accessible and inclusive to be positioned to welcome and celebrate our diverse sangha. Your bid will outline briefly what accessible and inclusive means for all venues being proposed. The very composition of your host community illustrates your commitment to inclusion, diversity and accessibility."

**Comment by nutjob4life** [comment]
In future, please include the URL of the page to be updated. I had to search around for a bit before I realized this isn't the "Bid Requirements Bulletin" but the Sangha Summit 2021 bulletin! 😂

Post updated! Please see the permalink at: https://recoverydharma.org/requesting-bids-for-the-2021-sangha-summit

**Comment by KrisRecoveryDharma** [comment]
The publish date for the Bid document is 10/20/2020.  Please change date for the publish date to 11/27/2020 so that it will show above the announcement for the President's townhall and below the announcement for the Board Elections.
