### ISSUE TITLE
Upload Minutes and Treasurers Report to Firespring Content Folder

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#29]
RD Board Meeting Minutes and Treasurer Reports are folders 8 and 9 of the content for Firespring. 
https://drive.google.com/drive/folders/1L1qedPRAZCevGUS0I71E7UWsJj-y21Zm?usp=sharing

I, Kris, find that I do not know the location of the public version of these documents. I do see them in our Recovery Dharma Drive, but I am uncertain about how to transfer them to these Firespring Files. 

I need technical assistance - or perhaps easier - have someone with the technical skills and access to complete the task. 

This is a top priority because it is an aspect of the home page and is holding up that process.

**Comment by nutjob4life** [comment]
Nothing too magic about this:

- I just clicked each board meeting and each treasurer report one at time with my browser while visiting https://recoverydharma.org/about-our-nonprofit …downloading each file to my computer
- I then dragged each file from my computer into the Google Drive browser window opened to folders 8 and 9.

Not high tech at all, just brute force! ☺️

**Comment by KrisRecoveryDharma** [comment]
Ahh!  It was the downloading bit that escaped my realm of possibilities.
Thank you!
Kris
