### ISSUE TITLE
Board members

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#3]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ ] new content
- [ ] replacing existing content
- [X ] deleting content

Please take Dirk and Critter photos and names off the Board of Directors page: https://recoverydharma.org/about/board-of-directors
thank you!

**Comment by nutjob4life** [comment]
Hi @Lacey-boop thanks for the notice. I've removed Dirk & Critter. You can see the updated page at https://recoverydharma.org/about/board-of-directors and here is a screen shot.

![Screen Shot 2020-08-26 at 4 33 30 PM](https://user-images.githubusercontent.com/814813/91359331-f98db080-e7b9-11ea-8920-389c0181bd79.png)
