### ISSUE TITLE
Bulletin - RDG Board Elections 2021

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#30]
## 📕 Summary

The Board Elections Document needs to be loaded onto the Bulletin

https://docs.google.com/document/d/e/2PACX-1vQTum1ttCnga8Pe6JGRdKTpfNUycoeHZvxjD5dZjLVrqa-yYueO879JmPsfl_Nu64inknvj8MzN81_a/pub

Replace this with a brief description of the content you want changed. Make sure to check if this is
- X new content

## 🔍 Details

- Title - Replace this with detailed information about the request. For new content, make sure to mention
 
- summary - Announcement of opening of Board Nominations
- Where - Bulletin
-  Hyperlink - https://recoverydharma.org/board/elections/2021/nominations-announement
I don't feel too confident about creating hyperlinks.  Let me know if there is a better alternative. 

## 📈 Attachments

For new content, don't forget to attach the file you want uploaded to the portal. If it's just text, you can even paste or type it in right here.

Recovery Dharma Global Board Elections 2021

Recovery Dharma Global (RDG) Board of Directors is opening nominations for the upcoming board election. The board currently has seven open seats. This is an excellent opportunity for those who are engaged in Recovery Dharma, committed to utilizing the Eightfold Path, and cultivating lovingkindness to share their skills, perspective, and experience with our community. 

We have taken inventory of the needs of the organization and the resources available through the five current directors. Additionally, we have engaged with members during the Summit, town halls, social media forums, and direct outreach. The following list summarizes the skills and qualities needed in the coming year. Engagement in and practice of the Eightfold path along with a commitment to the principles of diversity are important attributes of all board members. The skills listed below are specific to various committees of the board.

RDG is committed to practices of inclusion, diversity, equity, and accessibility. This includes creating a board that reflects the diversity of the Recovery Dharma by using a nomination committee approach to reach out to under-represented members or affinity groups and by producing targeted e-flyers to be posted on social media sent to members and announced at meetings.

Money Matters: Professional experience as a CPA, bookkeeper, and/or financial advisor. 
Fundraising: Forecasting, planning, budgeting, publicity, recruiting/overseeing volunteers, donor and community outreach, financial reporting/compliance, for both active and passive fundraising endeavors.
Archives: We need a person to oversee the creation of an infrastructure to preserve and maintain the records and artifacts of the RDG to promote transparency, accessibility, and the historical integrity of the organization. Ideally, this person will have experience implementing web-based electronic archival systems.
Literature Plus: We have heard the call from the community for expanding the resources available to the RD Community. This work requires a  skilled writer with experience working in a group setting to prioritize the subject matter,  community outreach, draft and edit literature for RDG approval and distribution. We’d especially love to hear from people with experience writing using inclusive and trauma-informed language. 
Administration: In the next year the board will continue ensuring that our core business functions and fiduciary duties are taken care of while we look ahead with both short and long-term strategic planning. To this end, it would be helpful to have directors who have organizational experience including budgeting, contracting, hiring, auditing, leading meetings, forecasting, and planning. 
Information Technology and Website: Calling all techies! Nearly everything we do as a board is done through an electronic forum. We currently utilize the website, Slack, Zoom, Google Docs, Google Drive, Survey Monkey, YouTube, Facebook, and email. In the coming year, we will look at the best use of technologies to serve the community by maximizing compatibility and accessibility.

If you are interested in joining the board sangha, and have questions or would like to discuss board service in more detail, you may follow up with any of your current RDG directors. We can each be reached by email at board@recoverydharma.org.

Timeline:
December - Nominations and Applications
December 5, 2020, 5 pm ET/ 2 pm PT - Townhall for questions about the election
January - Town halls with candidates
February - Election Week and Results announced
March - New Board Starts

In the coming weeks, we will be sharing additional information about the process for nominations and elections via the RDG Website, Newsletter, and Facebook Page. Look for messages from your current directors reflecting on our first year and the gifts of service. 

Yours in Loving Kindness,

Kris, Lacey, Joel, Kara & Amanda

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma see a preview at https://recoverydharma.org/board-elections-2021

Does this look all right?

**Comment by KrisRecoveryDharma** [comment]
Excellent! Thank you!

**Comment by KrisRecoveryDharma** [comment]
Please add this line underneath the title in the bulletin

Recovery Dharma Global (RDG) Board of Directors is opening nominations for the upcoming board election.

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma does this look right?  https://recoverydharma.org/board-elections-2021

**Comment by KrisRecoveryDharma** [comment]
Perfect! Thank you
