### ISSUE TITLE
Update from the Summit Sangha Committee 

### ISSUE THREAD

**Issue by joelro87** [RecoveryDharma/website#31]
Hi, this is an update from the Sangha Summit Committee to be placed as a new bulletin. 

"Hi Recovery Dharma Sangha!

A reminder that the Sangha Summit Committee is looking for interested host cities for the 2021 Sangha Summit in July! Details at the link below!

Our current plan for 2021 is a hybrid event that combines in person workshops with video access for members across the globe. Host cities will help us find physical spaces in the community that will help us realize this vision. Of course, we are operating in uncertain times with COVID-19, so if the event needs to be completely online, then it is our hope that the host committee can shift to help us host the online event. The Committee will be following all suggested federal, state, and local guidelines for safety regarding COVID-19. More details will be available soon. 

The ideal location would be relatively easy to travel to and have access to a space that supports our needs including a plenary hall and breakout rooms that are set up for hybrid events. All venues need to be accessible and inclusive to be positioned to welcome and celebrate our diverse sangha. Your bid will outline briefly what accessible and inclusive means for all venues being proposed. The very composition of your host community illustrates your commitment to inclusion, diversity and accessibility. It is our hope that the host community will also be in the position to grow and deepen their community from this experience. 

Our next meeting will be **Thursday, December 3, 2020, at 8 pm ET / 5 pm PT**. Feel free to join us for any questions regarding the host city bids or COVID-19 protocols. If you are already working on a bid, please join us at the meeting or reach out to let us know your bid is coming. We are happy to discuss ideas for bids to provide feedback before final submission.

Please email conference@recoverydharma.org for Zoom information or with any questions. 

https://recoverydharma.org/requesting-bids-for-the-2021-sangha-summit

Thank you,
2021 Sangha Summit Committee"

**Comment by nutjob4life** [comment]
Posted; see https://wp.me/p9QaBE-5xb
