### ISSUE TITLE
Wishlist idea:  Sectioned PDF version of Book

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#32]
## 📕 Summary

This is on a wish list priority, so getting to it as we have time.  It would be very helpful, though the have a sectioned version of the PDF of the book.  Here is an example from AA: 
https://www.aa.org/pages/en_US/alcoholics-anonymous

Replace this with a brief description of the content you want to be changed. Make sure to check if this is
- [X] new content

Make sure you mention URLs! Tell where the content should appear, get changed, be deleted, etc.

Suggested URL
https://recoverydharma.org/book-pages

## 🔍 Details

Replace this with detailed information about the request. For new content, make sure to mention
-  Recovery Dharma Book - Pages
- PDF version of the book, Recovery Dharma book, divided by chapters.
- Where should it live? https://recoverydharma.org/book
- How should it be hyperlinked? https://recoverydharma.org/book-pages

Also possible to add to the bottom of Book page rather than creating a new, different page. 

Inspiration page:  https://www.aa.org/pages/en_US/alcoholics-anonymous

## 📈 Attachments

Timing / Staffing:  
This is a good project for a new team member who has the time and skills to work on this wishlist of a project.

**Comment by unity1979** [comment]
Would love to help with this project.

**Comment by KrisRecoveryDharma** [comment]
Okay, Thom, consider it yours!

I was thinking that we would be using this version of the book: https://recoverydharma.org/wp-content/uploads/misc-content/Recovery_Dharma-v1.0.pdf

It matches up in page numbers and it seems to be more accessible to more people. 

thoughts?

**Comment by KrisRecoveryDharma** [comment]
I say go wtih the table of contents.  
We do also want to try to keep the page numbers so that those in a meeting who are using the paper book and those who are reading on line will be able to  each find the page with ease. 

Not sure if that is possible, but I thought I'd put it out there.

**Comment by unity1979** [comment]
Awesome!  Agreed 100% with keeping the page numbers.

Re page overlap: Some sections of the Eightfold path overlap, starting halfway down the page. (e.g. Wise Understanding -> Wise Intention (pg 24)) 

If we're making separate PDFs for each section standing alone, do we can to do A B C D (or ___?) Here's a mockup
![image](https://user-images.githubusercontent.com/70724023/100806137-ca07c900-33e4-11eb-9c7d-97f03892b61f.png)

**Comment by KrisRecoveryDharma** [comment]
I think A is the strong winner here since it keeps the context, but also
creates a highlight.
That is a really fabulous alternative! I was a solution I didn't even
envision possible!
Thank you!
Kris

**Comment by unity1979** [comment]
Goodness, that took a little while :)  Here are all the sections broken up, with text faded, and page numbers and titles of sections.  I have also sectioned out the Heart Practices for good measure.

(In one zip:) [RD Book (Sectioned PDF Version 2020-12a).zip](https://github.com/RecoveryDharma/website/files/5690140/RD.Book.Sectioned.PDF.Version.2020-12a.zip)
❖
[Preface.07 - PREFACE.pdf](https://github.com/RecoveryDharma/website/files/5690033/Preface.07.-.PREFACE.pdf)
[Preface.08-11 - Introduction-What is Recovery Dharma.pdf](https://github.com/RecoveryDharma/website/files/5690034/Preface.08-11.-.Introduction-What.is.Recovery.Dharma.pdf)
[Preface.12-14 - Where to Begin.pdf](https://github.com/RecoveryDharma/website/files/5690036/Preface.12-14.-.Where.to.Begin.pdf)
[Preface.15-16 - The Practice.pdf](https://github.com/RecoveryDharma/website/files/5690037/Preface.15-16.-.The.Practice.pdf)
❖
[RD.01-03 - Awakening - BUDDHA.pdf](https://github.com/RecoveryDharma/website/files/5690095/RD.01-03.-.Awakening.-.BUDDHA.pdf)
[RD.03-05 - The Story of the Original Buddha.pdf](https://github.com/RecoveryDharma/website/files/5690096/RD.03-05.-.The.Story.of.the.Original.Buddha.pdf)
[RD.05-06 - Walking in the Footsteps of the Buddha.pdf](https://github.com/RecoveryDharma/website/files/5690097/RD.05-06.-.Walking.in.the.Footsteps.of.the.Buddha.pdf)
[RD.07 - The Truth - DHARMA.pdf](https://github.com/RecoveryDharma/website/files/5690098/RD.07.-.The.Truth.-.DHARMA.pdf)
[RD.08-13 - The 1st Noble Truth.pdf](https://github.com/RecoveryDharma/website/files/5690099/RD.08-13.-.The.1st.Noble.Truth.pdf)
[RD.14-16 - The 2nd Noble Truth.pdf](https://github.com/RecoveryDharma/website/files/5690100/RD.14-16.-.The.2nd.Noble.Truth.pdf)
[RD.17-18 - The 3rd Noble Truth.pdf](https://github.com/RecoveryDharma/website/files/5690101/RD.17-18.-.The.3rd.Noble.Truth.pdf)
[RD.19-20 - The 4th Noble Truth.pdf](https://github.com/RecoveryDharma/website/files/5690102/RD.19-20.-.The.4th.Noble.Truth.pdf)
[RD.21-24 - Wise Understanding - THE EIGHTFOLD PATH.pdf](https://github.com/RecoveryDharma/website/files/5690103/RD.21-24.-.Wise.Understanding.-.THE.EIGHTFOLD.PATH.pdf)
[RD.24-33 - Wise Intention + Heart Practices.pdf](https://github.com/RecoveryDharma/website/files/5690104/RD.24-33.-.Wise.Intention.%2B.Heart.Practices.pdf)
[RD.33-36 - Wise Speech.pdf](https://github.com/RecoveryDharma/website/files/5690105/RD.33-36.-.Wise.Speech.pdf)
[RD.36-39 - Wise Action + 5 Precepts.pdf](https://github.com/RecoveryDharma/website/files/5690106/RD.36-39.-.Wise.Action.%2B.5.Precepts.pdf)
[RD.40-41 - Wise Livelihood.pdf](https://github.com/RecoveryDharma/website/files/5690107/RD.40-41.-.Wise.Livelihood.pdf)
[RD.41-43 - Wise Effort.pdf](https://github.com/RecoveryDharma/website/files/5690108/RD.41-43.-.Wise.Effort.pdf)
[RD.43-63 - Wise Mindfulness.pdf](https://github.com/RecoveryDharma/website/files/5690109/RD.43-63.-.Wise.Mindfulness.pdf)
[RD.48-51 - Wise Concentration.pdf](https://github.com/RecoveryDharma/website/files/5690110/RD.48-51.-.Wise.Concentration.pdf)
[RD.52-54 - Community - SANGHA.pdf](https://github.com/RecoveryDharma/website/files/5690111/RD.52-54.-.Community.-.SANGHA.pdf)
[RD.55-59 - Isolation and Connection.pdf](https://github.com/RecoveryDharma/website/files/5690112/RD.55-59.-.Isolation.and.Connection.pdf)
[RD.59-62 - Working with Others.pdf](https://github.com/RecoveryDharma/website/files/5690113/RD.59-62.-.Working.with.Others.pdf)
[RD.62-64 - Wise Friends and Mentors.pdf](https://github.com/RecoveryDharma/website/files/5690114/RD.62-64.-.Wise.Friends.and.Mentors.pdf)
[RD.64-67 - Service and Generosity.pdf](https://github.com/RecoveryDharma/website/files/5690115/RD.64-67.-.Service.and.Generosity.pdf)
[RD.68-87 - Recovery is Possible - SUMMARY.pdf](https://github.com/RecoveryDharma/website/files/5690116/RD.68-87.-.Recovery.is.Possible.-.SUMMARY.pdf)
[RD.73-74 - MEDITATIONS.pdf](https://github.com/RecoveryDharma/website/files/5690117/RD.73-74.-.MEDITATIONS.pdf)
[RD.75-79 - Basic Meditation.pdf](https://github.com/RecoveryDharma/website/files/5690118/RD.75-79.-.Basic.Meditation.pdf)
[RD.80-83 - Metta (Lovingkindness) Meditation.pdf](https://github.com/RecoveryDharma/website/files/5690119/RD.80-83.-.Metta.Lovingkindness.Meditation.pdf)
[RD.84-87 - Forgiveness Meditation.pdf](https://github.com/RecoveryDharma/website/files/5690120/RD.84-87.-.Forgiveness.Meditation.pdf)
[RD.88-91 - Equanimity Meditation.pdf](https://github.com/RecoveryDharma/website/files/5690122/RD.88-91.-.Equanimity.Meditation.pdf)
[RD.92-102 - QUESTIONS FOR INQUIRY.pdf](https://github.com/RecoveryDharma/website/files/5690123/RD.92-102.-.QUESTIONS.FOR.INQUIRY.pdf)
[RD.103-104 - Glossary.pdf](https://github.com/RecoveryDharma/website/files/5690124/RD.103-104.-.Glossary.pdf)
[RD.105-112 - RECOVERY DHARMA MEETING FORMAT.pdf](https://github.com/RecoveryDharma/website/files/5690125/RD.105-112.-.RECOVERY.DHARMA.MEETING.FORMAT.pdf)
[RD.112 - DEDICATION OF MERIT.pdf](https://github.com/RecoveryDharma/website/files/5690126/RD.112.-.DEDICATION.OF.MERIT.pdf)
❖
[HeartPractices.25-26 - (Choice of) Generosity.pdf](https://github.com/RecoveryDharma/website/files/5690130/HeartPractices.25-26.-.Choice.of.Generosity.pdf)
[HeartPractices.26-27 - Appreciative joy.pdf](https://github.com/RecoveryDharma/website/files/5690131/HeartPractices.26-27.-.Appreciative.joy.pdf)
[HeartPractices.27-28 - Compassion.pdf](https://github.com/RecoveryDharma/website/files/5690132/HeartPractices.27-28.-.Compassion.pdf)
[HeartPractices.28-29 - Metta.pdf](https://github.com/RecoveryDharma/website/files/5690133/HeartPractices.28-29.-.Metta.pdf)
[HeartPractices.29-30 - (Choice of) Forgiveness.pdf](https://github.com/RecoveryDharma/website/files/5690134/HeartPractices.29-30.-.Choice.of.Forgiveness.pdf)
[HeartPractices.30-31 - Equanimity.pdf](https://github.com/RecoveryDharma/website/files/5690135/HeartPractices.30-31.-.Equanimity.pdf)

**Comment by unity1979** [comment]
@KrisRecoveryDharma where do we go from here?  Is there a simple way to get this on the next website?  this is exciting.

**Comment by KrisRecoveryDharma** [comment]
Keeping this active because this is related to the pdf question

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @Lacey-boop @unity1979 Is this something we want incorporated into the new website? Wondering if this issue is stale or not 😄

**Comment by unity1979** [comment]
This is closed since the new website contains this feature. (Verify @KrisRecoveryDharma ?)

**Comment by unity1979** [comment]
Closing—This feature is completed as seen @
https://recovery-dharma.flywheelsites.com/book/

<img width="576" alt="image" src="https://user-images.githubusercontent.com/70724023/153470177-bf2806a1-e08f-4463-84ac-ac152ed10cce.png">
