### ISSUE TITLE
New Bulletin

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#33]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [X ] new content
- [ ] replacing existing content
- [ ] deleting content

Doc to be added to: https://recoverydharma.org/bulletins

## 🔍 Details

Please upload Town Hall meeting minutes as a Bulletin entry. 

Intro should read: 
Please find the minutes for the September 2020 Board Town Hall in which we discussed the creation of a legal name and logo for the Recovery Dharma Board of Directors. with a link to this pdf:
[9_5_20 non profit branding TH minutes notes.pdf](https://github.com/RecoveryDharma/website/files/5623496/9_5_20.non.profit.branding.TH.minutes.notes.pdf)

**Comment by nutjob4life** [comment]
I've posted the minutes as a bulletin; see https://wp.me/p9QaBE-5xo

If this looks okay, please close the issue. If not, comment here and re-assign to me 🙏

**Comment by KrisRecoveryDharma** [comment]
It looks good to me

**Comment by Lacey-boop** [comment]
thanks!
