### ISSUE TITLE
mailing address update

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#34]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ ] new content
- [X ] replacing existing content
- [ ] deleting content

On the contact page https://recoverydharma.org/contact
please update the address with our new mailing address:
3439 NE Sandy Blvd # 827
Portland, OR 97232

thank you!

**Comment by nutjob4life** [comment]
@Lacey-boop I updated the page at https://recoverydharma.org/contact

- In used the full ZIP+4 code
- I put the address into international format*

If this passes muster, please go ahead and click Close. If not, comment and let me know what else to fix!

*We are an _international_ organization after all 😉

**Comment by KrisRecoveryDharma** [comment]
This looks great to me!

**Comment by Lacey-boop** [comment]
thanks!
