### ISSUE TITLE
Board of Directors change

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#35]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ ] new content
- [ ] replacing existing content
- [X ] deleting content

Please take Paul out of the list of Directors: https://recoverydharma.org/about/board-of-directors

thank you!

**Comment by nutjob4life** [comment]
@Lacey-boop I removed Paul A with prejudice. Please see the updated page at https://recoverydharma.org/about/board-of-directors

If this looks okay, please go ahead and click Close. If not, comment here and let me know!

**Comment by KrisRecoveryDharma** [comment]
Looks great! Thanks!
