### ISSUE TITLE
New Bulletin with Town Hall Minutes

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#36]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ X] new content
- [ ] replacing existing content
- [ ] deleting content

https://recoverydharma.org/bulletins
Title can be October 2020 Town Hall Meeting Minutes
The following are the minutes for the October 2020 Board Town Hall in which Board President Kris Roehling presented the new RD website and answered questions from the community.

[10_24 President's TH.txt](https://github.com/RecoveryDharma/website/files/5647886/10_24.President.s.TH.txt)

## 🔍 Details

Replace this with detailed information about the request. For new content, make sure to mention
- The title
- A summary paragraph of the content
- Where it should live on the Recovery Dharma site
- How it should be hyperlinked from existing pages

For changes, tell where and what should be changed. For deletions, tell what to delete and if redirections should be left behind.

## 📈 Attachments

For new content, don't forget to attach the file you want uploaded to the portal. If it's just text, you can even paste or type it in right here.

**Comment by nutjob4life** [comment]
Published https://wp.me/p9QaBE-5xw

**Comment by Lacey-boop** [comment]
thanks Sean! 
Could you add this intro before you get into the minutes themself:

The following are the minutes for the October 2020 Board Town Hall in which Board President Kris Roehling presented the new RD website and answered questions from the community.

**Comment by nutjob4life** [comment]
Updated @Lacey-boop
