### ISSUE TITLE
2021 RDG Board Elections Page

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#37]
## 🤔 Tell Us About the Feature

2021 RDG Board Elections Page - It will include many documents;
Nomination documents:  7
Election Documents: TBD 

There is a URL for each document, and several documents have links.  A few of the documents are intended as Google Forms.  Like the website, this whole project is a LOT bigger than I anticipated.  But, if we want to be respectful, then nominees and members deserve all the information. 

I am tired at the moment, but wanted to give you a heads up that the final documents are on their way.  The IC is reviewing the Nomination documents. 4 of them will be ready on Monday 12-21-20.  They have until 1-2-21 for the other four.  More will be coming after that.   

## 🎇 What Solution You'd Like

Is it too soon to go ahead and just use the new site template? That would be an excellent solution for this page. 

## 〽️ Alternative Ideas

Alternatively - Create a page on the old site with the old format and a page on the new site with the new format. 

## 🗺 Context

This is the folder that contains all of the nomination documents.  The Inclusion Circle is reviewing them now - 4 are due on Monday, and 4 are due on 1/2/21.  There may be some edits from the IC, but I do not anticipate any major changes in format or function. 

I look forward to collaborating with you on further details - such as what format to use to present these and which template.  Thank you for all that you do. 

https://drive.google.com/drive/folders/18W46JiQVViVcM_aNsp0J-liOM5ap8K6k?usp=sharing

I will be available for the rest of this weekend and into next week.  My plans for the holidays are light this year. 

Kris

**Comment by nutjob4life** [comment]
Okay, I think this is a content update, not a new software feature. So I'm going to add a new page to the current production site with links to these 7 documents.

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma please see https://wp.me/p9QaBE-5xC

**Comment by KrisRecoveryDharma** [comment]
Sean,
Thank you!  Yes, this is on it's way!  We have a few other edits to make
before making it public.

Dirk,
One of the edits, is that GSuites is not allowing me to share with
everyone. It is only allowing me to share with restricted or anyone in the
group. I need "anyone with the link can view" status. Help!

Thank you!

Kris

**Comment by KrisRecoveryDharma** [comment]
Please delete or hide the following links.
We want to publish the page asap, but the last three documents won't be available until next week. 

Questionnaire
Elections Meeting Announcement — General
Elections Meeting Announcement — Focused

**Comment by nutjob4life** [comment]
Last 3 links removed.
