### ISSUE TITLE
2021 RDG Nomination Acceptance Form

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#40]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [XX] new content
- [ ] replacing existing content
- [ ] deleting content

Make sure you mention URLs! Tell where the content should appear, get changed, be deleted, etc.

Instruction:  Create a new page that is an online Form for the 2021 Nominations.  Information from the form should be accessible to nomination@recoverydharma.org

URL for the page: https://recoverydharma.org/2021-board-elections/nomation-acceptance-form

Details: 

START
TITLE 1:  2021 Recovery Dharma Global (RDG) Board 
TITLE 2: Online Nomination Acceptance Form

CONTENT: Please review the bullet points.  Then, complete the fields at the bottom of this form to notify the RDG Nominations Committee that you have accepted or declined your nomination to run for the 2021 RDG Board.

SUB TITLE: I affirm the following: 
<BULLET POINTS>
I have read and understood the letter to nominees, including the timeline for the 2021 Recovery Dharma Global Board Election and the calculations for board terms. 
I have read and understood the letter to nominees, including the timeline for the 2021 Recovery Dharma Global Board Election and the calculations for board terms. 
I commit to learning, listening, and creating space for inclusion, diversity, equity, and accessibility (IDEA) on the RDG board and the Recovery Dharma Community.
The RDG Board is interdependent with the larger Recovery Dharma Sangha.  It is accountable to and draws on the energy, skill, and expertise of the community. This includes collaboration with RDG committee volunteers, RD circles, sangha groups, inter-sangha's, and individual members.
I am a member of a Recovery Dharma local, online, and/or inter-sangha.
I commit to practicing the Five Precepts as reflected in the RDG Bylaws and Recovery Dharma Core Intentions.
I will remain in contact with the RDG Nominations Committee during the election process. nomination@recoverydharma.org
I will endeavor to complete the Board Questionnaire by the due date and participate in at least one “Meet the Candidates” Town Hall. These are not required but are encouraged as part of the process. 
I will disclose any involvement, personal or professional, that may constitute a conflict of interest as defined by the bylaws
I will attend scheduled board meetings (currently the 2nd Sunday of each month), committee meetings (each board member serves on at least one committee), the annual meeting & summit, board development training, town halls, and other meetings and events scheduled by the board. 
I will commit the attention, effort, and time that is needed to complete projects, reports, and activities mindfully and in a timely fashion.
I will familiarize myself with RDG bylaws, policies, procedures, committees, website, and decision making processes. 
I will participate in board training and retreats, and cultivate specific knowledge, skills, and resilience in service of being an effective member of the RDG sangha. 
I will attend the first regularly scheduled Board meeting after the election, upon which the Board will agree to a future meeting schedule. 
I will attend the RDG Summit, including the Annual Conference at which the Annual Board meeting will also take place.
I will remain connected with members of the worldwide membership of Recovery Dharma throughout the year.
I would like to: 

SUB HEADER: Acceptance and Signature
FIELD: Radio button or check box.  Can choose only one:
___ Decline my nomination to the Recovery Dharma Global Board of Directors
___ Accept my nomination to the Recovery Dharma Global Board of Directors. 

FIELDS
Name: SHORT FIELD
Phone:  SHORT FIELD
Email:  SHORT FIELD
Mailing Address: LONG FIELD
Comments:  LONG FIELD

CONTENT
“Dana is not a plea or directive to ‘give,’ Dana is the natural and joyful expression of a giving heart.”
– Theravada teacher GloriaTaraniya Ambrosia
 
END

- Where it should live on the Recovery Dharma site - 
         https://recoverydharma.org/2021-board-elections
         Replace the link to the PDF version of this form with a link to this fillable online version of it. 

## 📈 Attachments
PDF Version of the form
https://docs.google.com/document/d/1dti-srxH2kVMIsfjcGf3hJxGN83--95xljHpfUxm_M0/edit

**Comment by KrisRecoveryDharma** [comment]
Lacey can help guide this from the Nomination Committee Perspective while I am on retreat. 
Be well all!
And than you for getting us to this point on our path! 

Kris

**Comment by tom-raley** [comment]
Happy to help! @nutjob4life what do we use for forms? And where does the data get stored then? Let me know and I’ll take a stab at it!

**Comment by KrisRecoveryDharma** [comment]
Hello! 
Note that on Monday, 12/28/20 12:23 pm  I updated the bullet points - to correct some typos and make one small content change. 

If you haven't been able to work with the text yet, then never mind. If you uploaded a copy of the text before that, then please update. 

Thank you!

Kris

**Comment by nutjob4life** [comment]
Hi @tom-raley: there's a form editor on WordPress. Once you log into `wp-admin`, click "Forms" on the left-side toolbar.

WAIT A MINUTE. Looks like you found it!

Okay, carry on! Ping me on Slack or here if you need help.
![Screen Shot 2020-12-29 at 8 43 30 PM](https://user-images.githubusercontent.com/814813/103326566-8d94b080-4a16-11eb-939a-5a107ae9bb5c.png)

**Comment by tom-raley** [comment]
@nutjob4life Ha, yeah I just started digging around and found it. Thanks though! Looks like it's pretty straightforward to use.

@Lacey-boop I just sent a test form, can you let me know if it hit the nomination@recoverydharma.org email account? If so, the draft of this can be viewed here: https://recoverydharma.org/?page_id=21313&preview=true

If you all think it looks good, we should be good to publish!

**Comment by KrisRecoveryDharma** [comment]
Looks good!

I am realizing, though that I need to actually reverse the size of the title headers. 
RDG line the "subheader" size
Nomination acceptance form the headers size

Thank you!

Kris
