### ISSUE TITLE
NYE and Day meetings 

### ISSUE THREAD

**Issue by joelro87** [RecoveryDharma/website#41]
Hi,

Here is the New Year's Eve and Day meetings. It is currently updated. It lists all of the meetings, with a confirmation column on the left side. Not sure if we'll get anymore. Is there anyway to get this on the website? 

Thanks,
Joel 

https://docs.google.com/spreadsheets/d/17zJ0gwLhvyroJBULVwbdmqotCb379gNZC7IMyyitFe0/edit#gid=0

**Comment by KrisRecoveryDharma** [comment]
It's almost there! Here are the last few things to post it as a bulletin.

1) make sure the document is stored in the RDG google drive.  In this case
the Meetings folder.

2) Make sure is set to anyone with the link can view

3) Write up a title and Introductory paragraph (25-50 words)

Post the link to the document and the write up here. We will migrate it to
the website Repository.

I am thinking g we will want to create an online form for the blog in the
future

**Comment by joelro87** [comment]
Hi, where is the meeting folder?

I will work on the writeup now.

Thanks,
Joel

**Comment by joelro87** [comment]
Writeup: https://docs.google.com/document/d/1QRXLwi1p6TqHHvhXI85w-VPetYPQskhMTJX8LNuHdgI/edit
Meeting List: https://docs.google.com/spreadsheets/d/17zJ0gwLhvyroJBULVwbdmqotCb379gNZC7IMyyitFe0/edit#gid=0

Not sure where to put it in the shared drive.

**Comment by KrisRecoveryDharma** [comment]
Sorry, I thought I put the link in, but I guess it didn't take. Here it is

Meeting List folder: https://drive.google.com/drive/folders/1j1rN_YT-y1CB-1-HMzXvT26bSNsHpuxm?usp=sharing

**Comment by joelro87** [comment]
Okay, uploaded both files to that folder.
