### ISSUE TITLE
URGENT: Remove references to 2020 and to Covid on the meeting list page

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#42]
Overview
The Meeting list page currently referrs to the meeting list as the 2020 Covid List. This is generating confusion on the part of members.  We need to remove references to 2020 and covid on the page.  The details follow: 

1. URL: https://recoverydharma.org/meeting-list

2. Page Title: Remove the current title and replace it with: Recovery Dharma Meeting LIst

3. Under the subheading "Add or Update a Meeting:"  Remove the words: "due to covid-19"

4. Under the subheading "About the Meeting List Process:" Delete the current content under this heading. Replace it with this content:

The year 2020 initiated many changes in our lives. One huge change is how we gather. In March of 2020, the number of Recovery Dharma online meetings skyrocketed from 20 to 267 in just two weeks. We created a spreadsheet that we believed would be a temporary solution. As the year has progressed, so has the spreadsheet.

We are now in the process of creating a new meeting list structure in concert with our new website. We hope to be up and running with that new site soon.

Thanks!

**Comment by KrisRecoveryDharma** [comment]
Hey Guys, 

Just checking in on this task.  Any obstacles?  

Kris

**Comment by tom-raley** [comment]
@KrisRecoveryDharma @nutjob4life I'm on it!

**Comment by KrisRecoveryDharma** [comment]
Hey Guys, 

This one is not complete yet. It got closed by accident. The page still says 2020. 

Thanks!

**Comment by tom-raley** [comment]
@KrisRecoveryDharma There was something funky going on last night with our wordpress back end and it looks like the changes I made didn't save. I made them again this morning and just published it, looks to be live on the site now. I'll wait to close this issue until you review.

**Comment by KrisRecoveryDharma** [comment]
Looks great! 
Thank you!
