### ISSUE TITLE
2 New Bulletins for ASAP

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#44]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ X] new content
- [ ] replacing existing content
- [ ] deleting content

Please add these 2 new bulletins asap, thank you!! 🙏💕
.https://recoverydharma.org/bulletins
[Elections Meeting Annoucement.pdf](https://github.com/RecoveryDharma/website/files/5935728/Elections.Meeting.Annoucement.pdf)

[Nominee Town Hall Bulletin.pdf](https://github.com/RecoveryDharma/website/files/5935725/Nominee.Town.Hall.Bulletin.pdf)

## 🔍 Details

Replace this with detailed information about the request. For new content, make sure to mention
- The title
- A summary paragraph of the content
- Where it should live on the Recovery Dharma site
- How it should be hyperlinked from existing pages

For changes, tell where and what should be changed. For deletions, tell what to delete and if redirections should be left behind.

## 📈 Attachments

For new content, don't forget to attach the file you want uploaded to the portal. If it's just text, you can even paste or type it in right here.

**Comment by Lacey-boop** [comment]
thank you! Could you give me the URLs to the 2 new bulletins so that I can add them to the landing page without having to wait for the site to refresh?

**Comment by nutjob4life** [comment]
In progress

**Comment by nutjob4life** [comment]
Announcement permalink: https://recoverydharma.org/2021-recovery-dharma-global-general-meeting-announcement

Town halls permalink: https://recoverydharma.org/2021-recovery-dharma-global-nominee-town-halls
