### ISSUE TITLE
Treasurer's Reports 

### ISSUE THREAD

**Issue by joelro87** [RecoveryDharma/website#46]
https://recoverydharma.org/about-our-nonprofit

Can we add a note to the section for Treasurer's Reports stating that all of the reports are now part of the Board Meeting Minutes? For example, August's Treasurer's Reports are found in the September 13 Board Meeting Minutes. 

Thanks

**Comment by tom-raley** [comment]
@KrisRecoveryDharma is this still relevant? This was before my time I think 😄

**Comment by KrisRecoveryDharma** [comment]
Resolved
