### ISSUE TITLE
Remove Jordan Kramer Biography

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#47]
Jordan Kramer has dropped out of the 2021 Board election race.  Please delete his nominee profile:

I believe the page will automatically update to re-order the candidates. 

https://recoverydharma.org/2021-board-elections/jordan-kramer
https://recoverydharma.org/2021-board-elections

Tom has been working on this, but I am assigning both Tom and Sean since it is an easy fix and I'm hoping to get the page updated asap. 

Thanks!

Kris

**Comment by tom-raley** [comment]
Done!
