### ISSUE TITLE
Bulletin for Web Developer

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#5]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ X] new content
- [ ] replacing existing content
- [ ] deleting content

Make sure you mention URLs! Tell where the content should appear, get changed, be deleted, etc.

https://recoverydharma.org/bulletins

## 🔍 Details

Please add this Bulletin:

WEBSITE REDESIGN REQUEST FOR PROPOSAL
Recovery Dharma is issuing a request for proposals to redesign and modernize our website and related digital assets. Our goal is to modernize the look and to improve user experience, especially with searching for meetings & events and sharing resources among members and volunteers. The scope of this project also includes training Recovery Dharma volunteers to use the tools.   For more information, link to our announcement about the project:

**Comment by nutjob4life** [comment]
Posted under "Bulletins"! 
![Screen Shot 2020-08-31 at 1 50 30 PM](https://user-images.githubusercontent.com/814813/91755573-f5cea500-eb90-11ea-8996-b8f93a1775fb.png)
