### ISSUE TITLE
Bulletin for today

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#50]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ X] new content
- [ ] replacing existing content
- [ ] deleting content

Hello could you please add the following bulletin to this page: https://recoverydharma.org/bulletins
[Town Hall 2_19 statement.pdf](https://github.com/RecoveryDharma/website/files/6011109/Town.Hall.2_19.statement.pdf)

thank you!

## 🔍 Details

Replace this with detailed information about the request. For new content, make sure to mention
- The title
- A summary paragraph of the content
- Where it should live on the Recovery Dharma site
- How it should be hyperlinked from existing pages

For changes, tell where and what should be changed. For deletions, tell what to delete and if redirections should be left behind.

## 📈 Attachments

For new content, don't forget to attach the file you want uploaded to the portal. If it's just text, you can even paste or type it in right here.

**Comment by nutjob4life** [comment]
Posted https://wp.me/p9QaBE-5BN
