### ISSUE TITLE
Jan 2021 Board minutes

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#51]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [X ] new content
- [ ] replacing existing content
- [ ] deleting content

Please add the Jan 2021 minutes to: https://recoverydharma.org/about-our-nonprofit
[202101 RD Board Min .pdf](https://github.com/RecoveryDharma/website/files/6037866/202101.RD.Board.Min.pdf)

**Comment by nutjob4life** [comment]
Added to https://recoverydharma.org/about-our-nonprofit
