### ISSUE TITLE
Voting link to nominee bio leads to empty page.

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#53]
## 🐛 Describe the Bug

This link from the voting ballot leads to "Nothing Found": 
https://recoverydharma.org/2021-board-elections/thom-tran
![image](https://user-images.githubusercontent.com/70724023/109864922-10a9d100-7c29-11eb-8ec7-091f07d7f773.png)
-->
![image](https://user-images.githubusercontent.com/70724023/109864956-199aa280-7c29-11eb-86f1-275287253052.png)

The content actually lives at:
https://recoverydharma.org/2021-board-elections/thomas-tran

(Perhaps redirect?)

## 📜 How To Reproduce

Put steps to reproduce the behavior here, **including URLs**, such as
1. Visit: https://recoverydharma.org/2021-board-elections/thom-tran
2. Notice error, that it leads to "Nothing Found"
3. Visit: https://recoverydharma.org/2021-board-elections/thomas-tran
4. Notice that the correct content lives there. 

Bug happens 100% of time

## 🔎 Expected Behavior

Expected behavior: The bio should show up, instead of "Nothing Found"

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/70724023/109865600-d856c280-7c29-11eb-9d4a-9ba10ac42bec.png)

## 🕵️‍♀️ Extra Details

This was reported to me by a Board Member, that electionbuddy.com was giving a broken link to Thomas Tran's bio. Thank you for correcting this!

**Comment by nutjob4life** [comment]
Thanks for the thorough bug report!

If this is on the ballot itself, it'll have to be fixed in ElectionBuddy. But poking around the ElectionBuddy setup, it might be impossible to change a running election:

![Screen Shot 2021-03-03 at 2 22 41 PM](https://user-images.githubusercontent.com/814813/109867494-2bca1000-7c2c-11eb-92aa-564bdc9d7eb3.png)

I'm not overly familiar with ElectionBuddy, so I've added @catpanclub to take a look.

**Comment by nutjob4life** [comment]
OH! Duh.

I'll add a redirect!

**Comment by catpanclub** [comment]
Yeah, I didn’t play in the Electionbuddy space much since I was on the
ballot last time around.

**Comment by nutjob4life** [comment]
Thanks @catpanclub.

@unity1979 there is now a transparent redirect; visiting `/2021-board-elections/thom-tran` gives a 301 permanently moved and sends the browser to `/2021-board-elections/thomas-tran`. Hope this helps.
