### ISSUE TITLE
Election Results Announcement 

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#54]
Replace this with a brief description of the content you want changed. Make sure to check if this is
- [X ] new content
- [ ] replacing existing content
- [ ] deleting content

Please create this page but hold off on publishing, we'll let you know when its good to go (waiting to hear back from a couple people) thank you!
[2021 Election Results Article .pdf](https://github.com/RecoveryDharma/website/files/6145464/2021.Election.Results.Article.pdf)

**Comment by nutjob4life** [comment]
Hi @Lacey-boop, I'm re-assigning this @tom-raley. I am absolutely swamped this week.
