### ISSUE TITLE
Youtube town halls

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#56]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ ] new content
- [ ] replacing existing content
- [X ] deleting content

When you get an opportunity, please take down the following videos from our youtube channel:
https://www.youtube.com/watch?v=7HBNEQD9S1U&t=3777s
https://www.youtube.com/watch?v=eBh1doIuFww&t=2312s
https://www.youtube.com/watch?v=AJORGDWxUO8&t=177s

thank you!

## 🔍 Details

Replace this with detailed information about the request. For new content, make sure to mention
- The title
- A summary paragraph of the content
- Where it should live on the Recovery Dharma site
- How it should be hyperlinked from existing pages

For changes, tell where and what should be changed. For deletions, tell what to delete and if redirections should be left behind.

## 📈 Attachments

For new content, don't forget to attach the file you want uploaded to the portal. If it's just text, you can even paste or type it in right here.

**Comment by nutjob4life** [comment]
3 videos removed from the channel
