### ISSUE TITLE
AAPI Bulletin

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#59]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ X] new content
- [ ] replacing existing content
- [ ] deleting content

at: https://recoverydharma.org/bulletins

Bulletin Subject: RD AAPI Statement of Support

content:

The Recovery Dharma Global Board of Directors supports the following [Statement of Support](http://bit.ly/rd-aapi-statement) created by Recovery Dharma’s Asian American Pacific Islander (AAPI) community and encourages our community members around the world to add their signatures in support.

[RD AAPI Statement of Support](https://docs.google.com/forms/d/e/1FAIpQLSdgUERFdtJhfPXg_FGLFEWXUkbqfcv6EzXmJ0f88nxFbNQaPQ/viewform)

**Comment by nutjob4life** [comment]
Published at https://wp.me/p9QaBE-5Cx

**Comment by unity1979** [comment]
Is this supposed to be shown at www.recoverydharma.org/bulletin ? I don't see it there 

![image](https://user-images.githubusercontent.com/70724023/114463264-0ddfbb80-9b99-11eb-93c1-1f9b33cb0ae4.png)

**Comment by nutjob4life** [comment]
@unity1979 it's live from what I can tell. It shows up for me.

OH! Ah, I'm logged in. Non-logged-in users are getting a cached view.

Stoute installed Nginx advanced caching (without notifying us) and there's an extra step to getting content on the site: press the big red "Purge Entire Cache" button.

I would normally document this on a [wiki page here](https://github.com/RecoveryDharma/website/wiki) except we're leaving the old web host behind.

**Comment by nutjob4life** [comment]
Also replied on: https://rdcollective.slack.com/archives/CMGUMAQ49/p1618262182001100?thread_ts=1618254783.000200&cid=CMGUMAQ49
