### ISSUE TITLE
meeting changes email not working

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#6]
## 📕 Summary

The RD meeting email is not working- I got a bounce back today when I tested it. The emails from people about updating meeting changes are all coming to the info@ email now. 

Could you look into it? Maybe its just written incorrectly on the [page](https://recoverydharma.org/meeting-list)this is how it reads now: RDMtgList@RecoveryDharma.org

thank you!

**Comment by KrisRecoveryDharma** [comment]
Message was just sent to Dirk who will create the emails.  Web will be directed to Sean.  Meeting will be directed to Craig and Kris

**Comment by KrisRecoveryDharma** [comment]
Timeline is to have the emails working by 9/1/20

**Comment by KrisRecoveryDharma** [comment]
The emails will be Meetings@recoverydharma.org and Web@recoverydharma.org

**Comment by KrisRecoveryDharma** [comment]
Please cha ge the email address on this page:

URL:
https://recoverydharma.org/meeting-list

ADD OR UPDATE A MEETING
Submit meeting changes due to Covid-19
Submit new information
If follow up is needed, contact

>> should read: Meetings@RecoveryDharma.org

**Comment by Lacey-boop** [comment]
Hi it looks like the inquiry email on [this page](https://recoverydharma.org/meeting-list) still needs to be changed to meetings@recoverydharma.org

**Comment by nutjob4life** [comment]
@Lacey-boop done.
