### ISSUE TITLE
Homepage button promoting summit

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#61]
# ✋ Hold it!

Before you submit this request, remember that our webiste is a _content management system_. If you have an account on it, why not [try doing it yourself](https://recoverydharma.org/wp-login.php)?

If you don't have an account, then delete the above ⬆ and fill out below ⬇

## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ ] new content

Hi!! Can you create something on the homepage to promote and lead people to the Summit Landing Page-- it can read something like Registration for the 2021 Sangha Summit is Open! and have it lead to here: https://recoverydharma.org/conferences/2021-sangha-summit

thank you!

**Comment by tom-raley** [comment]
@Lacey-boop Just added this. Does it look great? No. But I think it does the job. Let me know if it should be changed at all.
