### ISSUE TITLE
Contact Email Update

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#7]
Find and replace Contact emails for Website Coordinator and Meeting List Coordinator

New emails: 
Web@recoverydharma.org
Meetings@recoverydharma.org

Just tracking here so I am notified as soon as complete so I can make announcement about new list.

**Comment by nutjob4life** [comment]
So far as I know, `web@recoverydharma.org` is now active.

When `meetings@` is ready, I'll go ahead and update the site, @KrisRecoveryDharma 😀

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma texted me:

> Craig reports he just confirmed the email

So I will go ahead and make all the updates!

(Next time Kris, feel free to comment here directly 🤗)

**Comment by nutjob4life** [comment]
Made the following updates:

- On the page https://recoverydharma.org/meeting-list, `RDMtgList@RecoveryDharma.org` → `meetings@RecoveryDharma.org`
- On the page https://recoverydharma.org/contact, changed `GitHub` to `Tech Suport`, added email `web@RecoveryDharma.org`.

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma this issue is now closed.

If there are further refinements you'd like related to this change, add a comment in the box below and click the white "Reopen and comment" button. Or submit a brand new issue by clicking the green "New issue" at the upper right.
