### ISSUE TITLE
Updates to WP site

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#78]
Hi Tom, can we also make a date to just go through the whole site looking for and fixing typos.
Requesting a few changes here:
https://docs.google.com/document/d/1AUL2Mce5wPlBvsEh0hHr4thb1Xc5H480jT30-9VQAR0/edit#

**Comment by raleytom** [comment]
@Lacey-boop yes we can definitely set a time. I start a new job next week and then am out of town, so not sure what my schedule looks like but I will circle back once I know more!

**Comment by tom-raley** [comment]
@Lacey-boop yes we can definitely set a time. I start a new job next week and then am out of town, so not sure what my schedule looks like but I will circle back once I know more!
