### ISSUE TITLE
Create Sheet for In Person Meeting

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#8]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [X ] new content
- [ ] replacing existing content
- [ ] deleting content

We need to create a Report Sheet that pulls and shows the In Person Meetings for Recovery Dharma. At this point, there are only 5 meetings, but they need representation.  Hopefully, we will be back to a full feature database by November. Until then, we need a temporary report sheet for these meetings.

One step in this process is above my ability - copy an array from one sheet to another. Once we copy it, I can format the new sheet to filter and show just the in person meetings.   I have been trying to learn by tutorials, but that is not working. 

https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Comment by nutjob4life** [comment]
Where's the array @KrisRecoveryDharma? To what sheet does it need to be copied?

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma I think I see what you mean, but I'm terrible at Google Sheets.

Perhaps we should ask A Thomas Tran?

**Comment by KrisRecoveryDharma** [comment]
I am not sure I am using the right language, or if Array is the right tool.

I want to pull records from the Unsorted Sheet into a new sheet. This new
sheet would list all of the in person meetings. Right now, there are only
5, so they can all be listed together.  I am hopeful that before the list
becomes too large, the new database will be active.

**Comment by nutjob4life** [comment]
Sounds all good @KrisRecoveryDharma but this is outside of my skillset. I recommend assigning @unity1979.

**Comment by KrisRecoveryDharma** [comment]
Thom and Kris completed this task today.

**Comment by nutjob4life** [comment]
Thank you @KrisRecoveryDharma  and @unity1979! 🎉
