### ISSUE TITLE
Confusing order of eBooks: Paperbacks not grouped together, eBooks not group together

### ISSUE THREAD

**Issue by unity1979** [RecoveryDharma/website#80]
Where: [https://recoverydharma.org/book](https://recoverydharma.org/book)

## 🤔 Tell Us About the Feature

The e-reader book versions (ePub and Kindle) can be grouped together for clarity.
The paperback book versions (PDF and Buy a Copy) can be grouped together as well.

This is how it's looked and it's confusing:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/70724023/131025314-5468edea-fd62-49b3-99c5-69a6de276827.png">

## 🎇 What Solution You'd Like

1. Swap positions of:
"Download Paperback PDF" ↔ "Download ePub (iOS/Google compatible)"

## 〽️ Alternative Ideas
2. Also, Kris mentioned that the "Download a Printable Copy" creates further confusion as well, since the page numbers don't match up-- would it be helpful to discuss removing the 8.5x11 rd book link, @KrisRecoveryDharma / @Lacey-boop ?

## 🗺 Context

This grouping would offer clarity
![image](https://user-images.githubusercontent.com/70724023/131026704-52bf82d9-46c7-4a8e-8d9d-8aa816aa244e.png)

**Comment by unity1979** [comment]
Closing issue since it is related to #57

**Comment by unity1979** [comment]
@tom-raley Thanks tom for clearing these out. This item is outdated and is actually still open, it should look like this:
![image](https://user-images.githubusercontent.com/70724023/139902762-10fb3291-1f18-45b5-8f5c-bbcf6b5d567b.png)

in a nutshell:

[Buy a copy] [Download Paperback PDF]
[Download AZW3 (Kindle Compatible)] [Listen to the Book on Soundcloud]
[Listen to the Audiobook on Soundclou] [Listen to the Book on Apple Podcasts]

(Remove Download a Printable Copy]
(Remove Listen...Google Play since it is no longer working]

**Comment by tom-raley** [comment]
@unity1979 Cool, should be all updated now! Closing the issue.
