### ISSUE TITLE
Update Blog on New site

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#84]
# ✋ Hold it!
I have an account, but this task is beyond my capability

## 📕 Summary

Three actions to clean up the prepare the blog for the new website:
1. Pull all the latest articles to the new site
2. Tag all new articles using the new system
3.  Delete 10 event placeholders

1. Pull all of the latest new and bulletin posts from the old site to the new.
Request Tom or Sean complete this task
From: 
https://recoverydharma.org/bulletins
https://recoverydharma.org/newsletters
To: 
https://recovery-dharma.flywheelsites.com/blog/

2. Tag new articles - Kris can complete this tass

3. 10 event placeholders will be replaced by moved articles that will be tagged as events

Thanks!

Kris

**Comment by nutjob4life** [comment]
Removing myself from assignment as I absolutely do not have time to handle this. Good luck @tom-raley.

**Comment by unity1979** [comment]
Status update: Only 1 Bulletin Post is missing on the new site. 

2021-12-30 - January 2022 Sangha Summit Town Hall @
https://recoverydharma.org/january-2022-sangha-summit-town-hall

(Other than this, all of the 53 bulletin posts are imported)

**Comment by tom-raley** [comment]
@unity1979 I was gonna just wait until right before launch to do another import, since I've imported them a few times now and every time we post to the current site it gets out of date. So this one can stay open till right before launch :)

**Comment by KrisRecoveryDharma** [comment]
😍

I love it when  plan comes together ❤️
