### ISSUE TITLE
In Person Meeting List  Broken Link  on active site

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#87]
Hello, 

The link for the in-person meeting list is broken.

Web Page Where the link is found: 
https://recoverydharma.org/meeting-list

Also, the link from the menu is not working

URL for the specific spreadsheet:
https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?fbclid=IwAR3S9VWQhc7xX1gd2KaXsk-ILX0a_Q1Blki-uP-AF7IAKdRYAkxMcW6WcgI#gid=1492891510

**Comment by tom-raley** [comment]
Hey @KrisRecoveryDharma any idea how long it’s been like this? I don’t believe this is an issue with our site. The link opens fine for me in the Google sheets app, so it’s the correct link. I believe the issue is in Google’s end.

**Comment by KrisRecoveryDharma** [comment]
About 4 days

**Comment by KrisRecoveryDharma** [comment]
You are right, tho, it is working now.  The error was relirted go us by
others and then I received the error.  If I get the error again I will
screen shot it.

Thanks!

**Comment by tom-raley** [comment]
Yeah, my bad, I still don’t know what caused it, but updating the link fixed it. The research I did said our sheet might be becoming corrupt, so we should keep an eye on it. Won’t be an issue much longer though ☺️
