### ISSUE TITLE
New WP site Bylaws

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#89]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ X] new content
- [ ] replacing existing content
- [ ] deleting content

Could you add our updated Bylaws to this page: https://recovery-dharma.flywheelsites.com/bylaws/
thank you!
[By-Laws Amendments 3.0.pdf](https://github.com/RecoveryDharma/website/files/7831323/By-Laws.Amendments.3.0.pdf)

**Comment by tom-raley** [comment]
@Lacey-boop I'm on it. Do we want this to be a PDF download that links to the PDF you provided? Or convert the PDF to HTML? The latter will take much longer, but is doable.

**Comment by Lacey-boop** [comment]
I think a pdf like the current website is ok

**Comment by tom-raley** [comment]
@Lacey-boop sounds good. Looking at it more, is the only place to access this document from the about page under Documents and Resources? Wondering if it makes sense to just have that card be a link to download the PDF instead of having an entire page for it. All good either way, just wanted to throw that out there :)

**Comment by Lacey-boop** [comment]
@tom-raley yeah if that link can just pop out a new page that has the pdf that would be great (new page thats just the pdf as opposed to automatic download would be great)

**Comment by tom-raley** [comment]
@Lacey-boop Cool, just added that as a link that opens in a new tab. The link is set up to open a new page that loads the PDF in the browser, but it is a browser specific setting that users set themselves that determines whether the PDF opens in the browser or whether it automatically downloads it, so we have no control over that in the code on the site. But as long as users have their browser set to open PDFs in the browser, this link will work.
