### ISSUE TITLE
Add links to In Person meetings and New Time Zone Tabs to Meeting List Page

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#9]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [X ] new content

Page to Change: Meeting List: **https://recoverydharma.org/meeting-list**

**Hyperlinks for New Meetings and Time Zones.** 
(In this order)

**In Person Meetings**  https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Hawaii**  https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Pacific US** https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Mountain US** https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Central US** https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Eastern US** https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**UK** https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Central Europe** https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Nepal** https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Japan** https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Australia** https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**New Zealand** https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Women Nonbinary Transgender** https://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma, It looks like the links above were copied from Facebook.

I'll see if I can remove the Facebook tracking codes.

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma, the page at https://recoverydharma.org/meeting-list is now updated.

**Comment by KrisRecoveryDharma** [comment]
Hmm..  I am confused. I copied them directly from the URL in the google sheet.  Maybe I should have use the "copy link" feature for sharing?

**Comment by KrisRecoveryDharma** [comment]
They are now updated with the "copy link" from the share menu in the google sheet.

**Comment by KrisRecoveryDharma** [comment]
I missed one on the list

**Women NonBinary** ttps://docs.google.com/spreadsheets/d/13sb_3p0pX-WLMnQP9kOszR1WE5LeeeamycD_carKn0g/edit?usp=sharing

And I missed requesting an update to the menu bar

**Comment by nutjob4life** [comment]
Re-opened on @KrisRecoveryDharma behalf for the above comment 🤗

**Comment by KrisRecoveryDharma** [comment]
Damit - one more

Atlantic:

**Comment by KrisRecoveryDharma** [comment]
Are you suggesting that we leave the zime zone list off of the menu because it takes too long to load? 

I can support that.

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma question: Where should Atlantic go? After "Eastern US" and before "UK"?

Also, no, I'm not suggesting we leave it off. It's not a loading speed issue. It's just that _changes_ to the menu take time to appear. Even if we changed _one letter_, it can take an hour for it to show up for everyone.

**Comment by KrisRecoveryDharma** [comment]
Yes, exactly!  Atlantic should be listed after eastern and before UK. 

Ohh!  Okay on the new content loading piece. 

Thank you !!!!

**Comment by nutjob4life** [comment]
Added "Atlantic" to the page https://recoverydharma.org/meeting-list and to the "Meetings" menu. It may take some time for these changes to appear (especially the menu) but they should be live any moment now. Here's a screenshot of the new menu:

![Screen Shot 2020-09-04 at 8 46 11 PM](https://user-images.githubusercontent.com/814813/92294223-dc5e8d80-eeef-11ea-9da6-d220bafff290.png)

If this is OK, please **say so as a comment and click "Close with comment"**. If not, please _say what else needs changing and click "Comment" instead_. Thank you! 🤗

**Comment by KrisRecoveryDharma** [comment]
It looks great! thank you!

**Comment by nutjob4life** [comment]
You are welcome. Thank you for your patience, @KrisRecoveryDharma!
