### ISSUE TITLE
Dharma wheel icon on WP site

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#92]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ X] new content
- [ ] replacing existing content
- [ ] deleting content

Hi Tom, 
Could you add the Dharma wheel icon (attached below in white) to the black dividers on the site.
Like this attached. But can you see if you can shorten the space above the wheel (don't need so much black there) and get rid of the line above "Our Program". And then do the same for all the black dividers? Like on the homepage another would be "Generosity". They're also on the Getting Started page, Meetings page, Books page ("Chapter by Chapter") etc etc
Or if you teach me how to do it, I can do these myself

thank you!
<img width="329" alt="Screen Shot 2022-01-30 at 8 56 33 PM" src="https://user-images.githubusercontent.com/70229948/151729215-2ef1918e-e804-4e29-bd09-dfc20e63d543.png">
![noun_Dharmachakra_740796 (1)](https://user-images.githubusercontent.com/70229948/151729225-7b7c4c8c-19df-4037-85be-5cf1cf4f8878.png)

**Comment by tom-raley** [comment]
@Lacey-boop I think I got them all. Let me know if any are missing!

**Comment by tom-raley** [comment]
@unity1979 Thanks! Updated those ones. Closing this now.
