### ISSUE TITLE
Change URL on title of new site

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/website#93]
Overview:  

On the Book page of the new site - change the URL for Buy a Book

Recovery Dharma URL: 
https://recovery-dharma.flywheelsites.com/book/

SECTION TWO
Highlight 1, Title: PURCHASE A COPYcC
Change the Link to the URL: 
https://www.amazon.com/Recovery-Dharma-Practices-Principles-Suffering/dp/1086040007/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1644025884&sr=8-3

**Comment by unity1979** [comment]
For clarity, the link that needs replacement looks like this:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/70724023/153475510-4d0ec462-cb55-48a7-a2a3-e367943278f1.png">
