### ISSUE TITLE
New WP Site design element update

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#95]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ ] new content
- [X ] replacing existing content
- [ ] deleting content

On the new site, on this page: https://recovery-dharma.flywheelsites.com/get-started/sangha-groups/
Could you make the little text blocks under the introparagraph look more like the "Documents and Resources" Blocks on the About page? https://recovery-dharma.flywheelsites.com/about/

**Comment by tom-raley** [comment]
Hey @Lacey-boop, take a look now. I think this is what you were going for (spacing issues in the top part with the cards). Let me know if this works https://recovery-dharma.flywheelsites.com/get-started/sangha-groups/

**Comment by Lacey-boop** [comment]
yess, looks good, thank you!
