### ISSUE TITLE
deleting image block

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#96]
## 📕 Summary

Replace this with a brief description of the content you want changed. Make sure to check if this is
- [ ] new content
- [ ] replacing existing content
- [X ] deleting content

Make sure you mention URLs! Tell where the content should appear, get changed, be deleted, etc.

Can you delete this image of the flower with RDG logo thats at the top of the page? When I go into the visual builder it asks me to start designing the page from scratch for some reason: https://recovery-dharma.flywheelsites.com/statement-against-oppression-of-all-kinds/
Also I'm not sure why it has that header? Is it supposed to live under the News? I don't see this listed when I scrolled through the News posts

**Comment by tom-raley** [comment]
@Lacey-boop Alright, removed that flower picture from all the posts. We can edit that header if we want, I'm not sure how its all supposed to be structured, as the News articles are all comingled with the blog articles, etc. but it's all listed under "Blog". So basically anything listed under Blog and written into the backend as a "Post" will have this format.
