### ISSUE TITLE
New website: Hide Diversity+Accessibility page

### ISSUE THREAD

**Issue by Lacey-boop** [RecoveryDharma/website#98]
## 📕 Summary

Can you hide the D+A page https://recovery-dharma.flywheelsites.com/resources/diversity-accessibility/
under Resources?

We're just asking some people to review it before we publish it.

thanks!

**Comment by tom-raley** [comment]
@Lacey-boop I left the page live at https://recovery-dharma.flywheelsites.com/resources/diversity-accessibility/ so people can review, but removed it from the menu so it won't be accessible anywhere on the site (I think) aside from direct URL.
